import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/providers/theme-provider";
// Side-effect import: initialises i18next before any component renders, so
// the first paint is already in the right language.
import "@/config/i18n";
import "./index.css";

// Auto generated by TanStack Router (DO NOT EDIT THIS FILE)
import { routeTree } from "./routeTree.gen";

// Calm defaults so a slow/unhealthy endpoint isn't hammered: one retry (not
// the default 3), no refetch on every window focus, and a 30s freshness window.
// Without this, a slow admin endpoint would be re-fired 3x per query and again
// on every tab focus, piling load onto an already-struggling server.
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      refetchOnWindowFocus: false,
      staleTime: 30_000,
    },
  },
});
const router = createRouter({
  routeTree,
  scrollRestoration: true,
  defaultPreload: "intent",
  defaultPreloadStaleTime: 0,
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <ThemeProvider
        defaultTheme="system"
        storageKey="vite-ui-theme"
      >
        <TooltipProvider>
          <RouterProvider router={router} />
          <Toaster />
        </TooltipProvider>
      </ThemeProvider>
    </QueryClientProvider>
  </StrictMode>,
);
