/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminErrorPreviewRouteImport } from './routes/admin/error-preview'
import { Route as AdminProtectedRouteImport } from './routes/admin/_protected'
import { Route as AdminPreviewRouteImport } from './routes/admin/_preview'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AdminProtectedTransactionsRouteRouteImport } from './routes/admin/_protected/transactions/route'
import { Route as AdminProtectedCategoriesRouteRouteImport } from './routes/admin/_protected/categories/route'
import { Route as AdminPreviewCategoriesPreviewRouteRouteImport } from './routes/admin/_preview/categories-preview/route'
import { Route as AdminProtectedTransactionsIndexRouteImport } from './routes/admin/_protected/transactions/index'
import { Route as AdminProtectedIntegrationIndexRouteImport } from './routes/admin/_protected/integration/index'
import { Route as AdminProtectedFinancialIndexRouteImport } from './routes/admin/_protected/financial/index'
import { Route as AdminProtectedDashboardIndexRouteImport } from './routes/admin/_protected/dashboard/index'
import { Route as AdminProtectedCategoriesIndexRouteImport } from './routes/admin/_protected/categories/index'
import { Route as AdminPreviewTransactionPreviewIndexRouteImport } from './routes/admin/_preview/transaction-preview/index'
import { Route as AdminPreviewIntegrationPreviewIndexRouteImport } from './routes/admin/_preview/integration-preview/index'
import { Route as AdminPreviewFinancePreviewIndexRouteImport } from './routes/admin/_preview/finance-preview/index'
import { Route as AdminPreviewDashboardPreviewIndexRouteImport } from './routes/admin/_preview/dashboard-preview/index'
import { Route as AdminPreviewCategoriesPreviewIndexRouteImport } from './routes/admin/_preview/categories-preview/index'
import { Route as AdminProtectedTransactionsManualIndexRouteImport } from './routes/admin/_protected/transactions/manual/index'
import { Route as AdminProtectedTransactionsAutomaticIndexRouteImport } from './routes/admin/_protected/transactions/automatic/index'
import { Route as AdminProtectedCategoriesSubCategoryIndexRouteImport } from './routes/admin/_protected/categories/sub-category/index'
import { Route as AdminProtectedCategoriesServerCategoryIndexRouteImport } from './routes/admin/_protected/categories/server-category/index'
import { Route as AdminProtectedCategoriesCategoryIndexRouteImport } from './routes/admin/_protected/categories/category/index'
import { Route as AdminProtectedCategoriesCategoryTypeIndexRouteImport } from './routes/admin/_protected/categories/category-type/index'
import { Route as AdminProtectedCategoriesCategoryProviderIndexRouteImport } from './routes/admin/_protected/categories/category-provider/index'
import { Route as AdminPreviewCategoriesPreviewSubCategoryIndexRouteImport } from './routes/admin/_preview/categories-preview/sub-category/index'
import { Route as AdminPreviewCategoriesPreviewServerCategoryIndexRouteImport } from './routes/admin/_preview/categories-preview/server-category/index'
import { Route as AdminPreviewCategoriesPreviewCategoryIndexRouteImport } from './routes/admin/_preview/categories-preview/category/index'
import { Route as AdminPreviewCategoriesPreviewCategoryTypeIndexRouteImport } from './routes/admin/_preview/categories-preview/category-type/index'
import { Route as AdminPreviewCategoriesPreviewCategoryProviderIndexRouteImport } from './routes/admin/_preview/categories-preview/category-provider/index'
import { Route as AdminProtectedCategoriesSubCategoryAddIndexRouteImport } from './routes/admin/_protected/categories/sub-category/add/index'
import { Route as AdminProtectedCategoriesCategoryAddIndexRouteImport } from './routes/admin/_protected/categories/category/add/index'
import { Route as AdminPreviewTransactionPreviewInvoiceNoEditIndexRouteImport } from './routes/admin/_preview/transaction-preview/$invoiceNo/edit/index'
import { Route as AdminPreviewCategoriesPreviewSubCategoryAddIndexRouteImport } from './routes/admin/_preview/categories-preview/sub-category/add/index'
import { Route as AdminPreviewCategoriesPreviewCategoryAddIndexRouteImport } from './routes/admin/_preview/categories-preview/category/add/index'
import { Route as AdminProtectedTransactionsManualInvoiceNoEditIndexRouteImport } from './routes/admin/_protected/transactions/manual/$invoiceNo/edit/index'
import { Route as AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRouteImport } from './routes/admin/_protected/transactions/automatic/$invoiceNo/edit/index'
import { Route as AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRouteImport } from './routes/admin/_protected/categories/sub-category/$subCategoryId/edit/index'
import { Route as AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRouteImport } from './routes/admin/_preview/categories-preview/sub-category/$subCategoryId/edit/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErrorPreviewRoute = AdminErrorPreviewRouteImport.update({
  id: '/admin/error-preview',
  path: '/admin/error-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/admin/_preview',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminProtectedTransactionsRouteRoute =
  AdminProtectedTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedCategoriesRouteRoute =
  AdminProtectedCategoriesRouteRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminPreviewCategoriesPreviewRouteRoute =
  AdminPreviewCategoriesPreviewRouteRouteImport.update({
    id: '/categories-preview',
    path: '/categories-preview',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminProtectedTransactionsIndexRoute =
  AdminProtectedTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedIntegrationIndexRoute =
  AdminProtectedIntegrationIndexRouteImport.update({
    id: '/integration/',
    path: '/integration/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedFinancialIndexRoute =
  AdminProtectedFinancialIndexRouteImport.update({
    id: '/financial/',
    path: '/financial/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedDashboardIndexRoute =
  AdminProtectedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedCategoriesIndexRoute =
  AdminProtectedCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminPreviewTransactionPreviewIndexRoute =
  AdminPreviewTransactionPreviewIndexRouteImport.update({
    id: '/transaction-preview/',
    path: '/transaction-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewIntegrationPreviewIndexRoute =
  AdminPreviewIntegrationPreviewIndexRouteImport.update({
    id: '/integration-preview/',
    path: '/integration-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewFinancePreviewIndexRoute =
  AdminPreviewFinancePreviewIndexRouteImport.update({
    id: '/finance-preview/',
    path: '/finance-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewDashboardPreviewIndexRoute =
  AdminPreviewDashboardPreviewIndexRouteImport.update({
    id: '/dashboard-preview/',
    path: '/dashboard-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewCategoriesPreviewIndexRoute =
  AdminPreviewCategoriesPreviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminProtectedTransactionsManualIndexRoute =
  AdminProtectedTransactionsManualIndexRouteImport.update({
    id: '/manual/',
    path: '/manual/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedTransactionsAutomaticIndexRoute =
  AdminProtectedTransactionsAutomaticIndexRouteImport.update({
    id: '/automatic/',
    path: '/automatic/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedCategoriesSubCategoryIndexRoute =
  AdminProtectedCategoriesSubCategoryIndexRouteImport.update({
    id: '/sub-category/',
    path: '/sub-category/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesServerCategoryIndexRoute =
  AdminProtectedCategoriesServerCategoryIndexRouteImport.update({
    id: '/server-category/',
    path: '/server-category/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesCategoryIndexRoute =
  AdminProtectedCategoriesCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesCategoryTypeIndexRoute =
  AdminProtectedCategoriesCategoryTypeIndexRouteImport.update({
    id: '/category-type/',
    path: '/category-type/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesCategoryProviderIndexRoute =
  AdminProtectedCategoriesCategoryProviderIndexRouteImport.update({
    id: '/category-provider/',
    path: '/category-provider/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewSubCategoryIndexRoute =
  AdminPreviewCategoriesPreviewSubCategoryIndexRouteImport.update({
    id: '/sub-category/',
    path: '/sub-category/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewServerCategoryIndexRoute =
  AdminPreviewCategoriesPreviewServerCategoryIndexRouteImport.update({
    id: '/server-category/',
    path: '/server-category/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewCategoryIndexRoute =
  AdminPreviewCategoriesPreviewCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewCategoryTypeIndexRoute =
  AdminPreviewCategoriesPreviewCategoryTypeIndexRouteImport.update({
    id: '/category-type/',
    path: '/category-type/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewCategoryProviderIndexRoute =
  AdminPreviewCategoriesPreviewCategoryProviderIndexRouteImport.update({
    id: '/category-provider/',
    path: '/category-provider/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminProtectedCategoriesSubCategoryAddIndexRoute =
  AdminProtectedCategoriesSubCategoryAddIndexRouteImport.update({
    id: '/sub-category/add/',
    path: '/sub-category/add/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesCategoryAddIndexRoute =
  AdminProtectedCategoriesCategoryAddIndexRouteImport.update({
    id: '/category/add/',
    path: '/category/add/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute =
  AdminPreviewTransactionPreviewInvoiceNoEditIndexRouteImport.update({
    id: '/transaction-preview/$invoiceNo/edit/',
    path: '/transaction-preview/$invoiceNo/edit/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewCategoriesPreviewSubCategoryAddIndexRoute =
  AdminPreviewCategoriesPreviewSubCategoryAddIndexRouteImport.update({
    id: '/sub-category/add/',
    path: '/sub-category/add/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewCategoryAddIndexRoute =
  AdminPreviewCategoriesPreviewCategoryAddIndexRouteImport.update({
    id: '/category/add/',
    path: '/category/add/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminProtectedTransactionsManualInvoiceNoEditIndexRoute =
  AdminProtectedTransactionsManualInvoiceNoEditIndexRouteImport.update({
    id: '/manual/$invoiceNo/edit/',
    path: '/manual/$invoiceNo/edit/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute =
  AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRouteImport.update({
    id: '/automatic/$invoiceNo/edit/',
    path: '/automatic/$invoiceNo/edit/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRoute =
  AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRouteImport.update({
    id: '/sub-category/$subCategoryId/edit/',
    path: '/sub-category/$subCategoryId/edit/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRoute =
  AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRouteImport.update(
    {
      id: '/sub-category/$subCategoryId/edit/',
      path: '/sub-category/$subCategoryId/edit/',
      getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/error-preview': typeof AdminErrorPreviewRoute
  '/admin/categories-preview': typeof AdminPreviewCategoriesPreviewRouteRouteWithChildren
  '/admin/categories': typeof AdminProtectedCategoriesRouteRouteWithChildren
  '/admin/transactions': typeof AdminProtectedTransactionsRouteRouteWithChildren
  '/login/': typeof AuthLoginIndexRoute
  '/admin/categories-preview/': typeof AdminPreviewCategoriesPreviewIndexRoute
  '/admin/dashboard-preview/': typeof AdminPreviewDashboardPreviewIndexRoute
  '/admin/finance-preview/': typeof AdminPreviewFinancePreviewIndexRoute
  '/admin/integration-preview/': typeof AdminPreviewIntegrationPreviewIndexRoute
  '/admin/transaction-preview/': typeof AdminPreviewTransactionPreviewIndexRoute
  '/admin/categories/': typeof AdminProtectedCategoriesIndexRoute
  '/admin/dashboard/': typeof AdminProtectedDashboardIndexRoute
  '/admin/financial/': typeof AdminProtectedFinancialIndexRoute
  '/admin/integration/': typeof AdminProtectedIntegrationIndexRoute
  '/admin/transactions/': typeof AdminProtectedTransactionsIndexRoute
  '/admin/categories-preview/category-provider/': typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRoute
  '/admin/categories-preview/category-type/': typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRoute
  '/admin/categories-preview/category/': typeof AdminPreviewCategoriesPreviewCategoryIndexRoute
  '/admin/categories-preview/server-category/': typeof AdminPreviewCategoriesPreviewServerCategoryIndexRoute
  '/admin/categories-preview/sub-category/': typeof AdminPreviewCategoriesPreviewSubCategoryIndexRoute
  '/admin/categories/category-provider/': typeof AdminProtectedCategoriesCategoryProviderIndexRoute
  '/admin/categories/category-type/': typeof AdminProtectedCategoriesCategoryTypeIndexRoute
  '/admin/categories/category/': typeof AdminProtectedCategoriesCategoryIndexRoute
  '/admin/categories/server-category/': typeof AdminProtectedCategoriesServerCategoryIndexRoute
  '/admin/categories/sub-category/': typeof AdminProtectedCategoriesSubCategoryIndexRoute
  '/admin/transactions/automatic/': typeof AdminProtectedTransactionsAutomaticIndexRoute
  '/admin/transactions/manual/': typeof AdminProtectedTransactionsManualIndexRoute
  '/admin/categories-preview/category/add/': typeof AdminPreviewCategoriesPreviewCategoryAddIndexRoute
  '/admin/categories-preview/sub-category/add/': typeof AdminPreviewCategoriesPreviewSubCategoryAddIndexRoute
  '/admin/transaction-preview/$invoiceNo/edit/': typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute
  '/admin/categories/category/add/': typeof AdminProtectedCategoriesCategoryAddIndexRoute
  '/admin/categories/sub-category/add/': typeof AdminProtectedCategoriesSubCategoryAddIndexRoute
  '/admin/categories-preview/sub-category/$subCategoryId/edit/': typeof AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRoute
  '/admin/categories/sub-category/$subCategoryId/edit/': typeof AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRoute
  '/admin/transactions/automatic/$invoiceNo/edit/': typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute
  '/admin/transactions/manual/$invoiceNo/edit/': typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/error-preview': typeof AdminErrorPreviewRoute
  '/login': typeof AuthLoginIndexRoute
  '/admin/categories-preview': typeof AdminPreviewCategoriesPreviewIndexRoute
  '/admin/dashboard-preview': typeof AdminPreviewDashboardPreviewIndexRoute
  '/admin/finance-preview': typeof AdminPreviewFinancePreviewIndexRoute
  '/admin/integration-preview': typeof AdminPreviewIntegrationPreviewIndexRoute
  '/admin/transaction-preview': typeof AdminPreviewTransactionPreviewIndexRoute
  '/admin/categories': typeof AdminProtectedCategoriesIndexRoute
  '/admin/dashboard': typeof AdminProtectedDashboardIndexRoute
  '/admin/financial': typeof AdminProtectedFinancialIndexRoute
  '/admin/integration': typeof AdminProtectedIntegrationIndexRoute
  '/admin/transactions': typeof AdminProtectedTransactionsIndexRoute
  '/admin/categories-preview/category-provider': typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRoute
  '/admin/categories-preview/category-type': typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRoute
  '/admin/categories-preview/category': typeof AdminPreviewCategoriesPreviewCategoryIndexRoute
  '/admin/categories-preview/server-category': typeof AdminPreviewCategoriesPreviewServerCategoryIndexRoute
  '/admin/categories-preview/sub-category': typeof AdminPreviewCategoriesPreviewSubCategoryIndexRoute
  '/admin/categories/category-provider': typeof AdminProtectedCategoriesCategoryProviderIndexRoute
  '/admin/categories/category-type': typeof AdminProtectedCategoriesCategoryTypeIndexRoute
  '/admin/categories/category': typeof AdminProtectedCategoriesCategoryIndexRoute
  '/admin/categories/server-category': typeof AdminProtectedCategoriesServerCategoryIndexRoute
  '/admin/categories/sub-category': typeof AdminProtectedCategoriesSubCategoryIndexRoute
  '/admin/transactions/automatic': typeof AdminProtectedTransactionsAutomaticIndexRoute
  '/admin/transactions/manual': typeof AdminProtectedTransactionsManualIndexRoute
  '/admin/categories-preview/category/add': typeof AdminPreviewCategoriesPreviewCategoryAddIndexRoute
  '/admin/categories-preview/sub-category/add': typeof AdminPreviewCategoriesPreviewSubCategoryAddIndexRoute
  '/admin/transaction-preview/$invoiceNo/edit': typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute
  '/admin/categories/category/add': typeof AdminProtectedCategoriesCategoryAddIndexRoute
  '/admin/categories/sub-category/add': typeof AdminProtectedCategoriesSubCategoryAddIndexRoute
  '/admin/categories-preview/sub-category/$subCategoryId/edit': typeof AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRoute
  '/admin/categories/sub-category/$subCategoryId/edit': typeof AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRoute
  '/admin/transactions/automatic/$invoiceNo/edit': typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute
  '/admin/transactions/manual/$invoiceNo/edit': typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin/_preview': typeof AdminPreviewRouteWithChildren
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/error-preview': typeof AdminErrorPreviewRoute
  '/admin/_preview/categories-preview': typeof AdminPreviewCategoriesPreviewRouteRouteWithChildren
  '/admin/_protected/categories': typeof AdminProtectedCategoriesRouteRouteWithChildren
  '/admin/_protected/transactions': typeof AdminProtectedTransactionsRouteRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/admin/_preview/categories-preview/': typeof AdminPreviewCategoriesPreviewIndexRoute
  '/admin/_preview/dashboard-preview/': typeof AdminPreviewDashboardPreviewIndexRoute
  '/admin/_preview/finance-preview/': typeof AdminPreviewFinancePreviewIndexRoute
  '/admin/_preview/integration-preview/': typeof AdminPreviewIntegrationPreviewIndexRoute
  '/admin/_preview/transaction-preview/': typeof AdminPreviewTransactionPreviewIndexRoute
  '/admin/_protected/categories/': typeof AdminProtectedCategoriesIndexRoute
  '/admin/_protected/dashboard/': typeof AdminProtectedDashboardIndexRoute
  '/admin/_protected/financial/': typeof AdminProtectedFinancialIndexRoute
  '/admin/_protected/integration/': typeof AdminProtectedIntegrationIndexRoute
  '/admin/_protected/transactions/': typeof AdminProtectedTransactionsIndexRoute
  '/admin/_preview/categories-preview/category-provider/': typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRoute
  '/admin/_preview/categories-preview/category-type/': typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRoute
  '/admin/_preview/categories-preview/category/': typeof AdminPreviewCategoriesPreviewCategoryIndexRoute
  '/admin/_preview/categories-preview/server-category/': typeof AdminPreviewCategoriesPreviewServerCategoryIndexRoute
  '/admin/_preview/categories-preview/sub-category/': typeof AdminPreviewCategoriesPreviewSubCategoryIndexRoute
  '/admin/_protected/categories/category-provider/': typeof AdminProtectedCategoriesCategoryProviderIndexRoute
  '/admin/_protected/categories/category-type/': typeof AdminProtectedCategoriesCategoryTypeIndexRoute
  '/admin/_protected/categories/category/': typeof AdminProtectedCategoriesCategoryIndexRoute
  '/admin/_protected/categories/server-category/': typeof AdminProtectedCategoriesServerCategoryIndexRoute
  '/admin/_protected/categories/sub-category/': typeof AdminProtectedCategoriesSubCategoryIndexRoute
  '/admin/_protected/transactions/automatic/': typeof AdminProtectedTransactionsAutomaticIndexRoute
  '/admin/_protected/transactions/manual/': typeof AdminProtectedTransactionsManualIndexRoute
  '/admin/_preview/categories-preview/category/add/': typeof AdminPreviewCategoriesPreviewCategoryAddIndexRoute
  '/admin/_preview/categories-preview/sub-category/add/': typeof AdminPreviewCategoriesPreviewSubCategoryAddIndexRoute
  '/admin/_preview/transaction-preview/$invoiceNo/edit/': typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute
  '/admin/_protected/categories/category/add/': typeof AdminProtectedCategoriesCategoryAddIndexRoute
  '/admin/_protected/categories/sub-category/add/': typeof AdminProtectedCategoriesSubCategoryAddIndexRoute
  '/admin/_preview/categories-preview/sub-category/$subCategoryId/edit/': typeof AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRoute
  '/admin/_protected/categories/sub-category/$subCategoryId/edit/': typeof AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRoute
  '/admin/_protected/transactions/automatic/$invoiceNo/edit/': typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute
  '/admin/_protected/transactions/manual/$invoiceNo/edit/': typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/error-preview'
    | '/admin/categories-preview'
    | '/admin/categories'
    | '/admin/transactions'
    | '/login/'
    | '/admin/categories-preview/'
    | '/admin/dashboard-preview/'
    | '/admin/finance-preview/'
    | '/admin/integration-preview/'
    | '/admin/transaction-preview/'
    | '/admin/categories/'
    | '/admin/dashboard/'
    | '/admin/financial/'
    | '/admin/integration/'
    | '/admin/transactions/'
    | '/admin/categories-preview/category-provider/'
    | '/admin/categories-preview/category-type/'
    | '/admin/categories-preview/category/'
    | '/admin/categories-preview/server-category/'
    | '/admin/categories-preview/sub-category/'
    | '/admin/categories/category-provider/'
    | '/admin/categories/category-type/'
    | '/admin/categories/category/'
    | '/admin/categories/server-category/'
    | '/admin/categories/sub-category/'
    | '/admin/transactions/automatic/'
    | '/admin/transactions/manual/'
    | '/admin/categories-preview/category/add/'
    | '/admin/categories-preview/sub-category/add/'
    | '/admin/transaction-preview/$invoiceNo/edit/'
    | '/admin/categories/category/add/'
    | '/admin/categories/sub-category/add/'
    | '/admin/categories-preview/sub-category/$subCategoryId/edit/'
    | '/admin/categories/sub-category/$subCategoryId/edit/'
    | '/admin/transactions/automatic/$invoiceNo/edit/'
    | '/admin/transactions/manual/$invoiceNo/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/error-preview'
    | '/login'
    | '/admin/categories-preview'
    | '/admin/dashboard-preview'
    | '/admin/finance-preview'
    | '/admin/integration-preview'
    | '/admin/transaction-preview'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/financial'
    | '/admin/integration'
    | '/admin/transactions'
    | '/admin/categories-preview/category-provider'
    | '/admin/categories-preview/category-type'
    | '/admin/categories-preview/category'
    | '/admin/categories-preview/server-category'
    | '/admin/categories-preview/sub-category'
    | '/admin/categories/category-provider'
    | '/admin/categories/category-type'
    | '/admin/categories/category'
    | '/admin/categories/server-category'
    | '/admin/categories/sub-category'
    | '/admin/transactions/automatic'
    | '/admin/transactions/manual'
    | '/admin/categories-preview/category/add'
    | '/admin/categories-preview/sub-category/add'
    | '/admin/transaction-preview/$invoiceNo/edit'
    | '/admin/categories/category/add'
    | '/admin/categories/sub-category/add'
    | '/admin/categories-preview/sub-category/$subCategoryId/edit'
    | '/admin/categories/sub-category/$subCategoryId/edit'
    | '/admin/transactions/automatic/$invoiceNo/edit'
    | '/admin/transactions/manual/$invoiceNo/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin/_preview'
    | '/admin/_protected'
    | '/admin/error-preview'
    | '/admin/_preview/categories-preview'
    | '/admin/_protected/categories'
    | '/admin/_protected/transactions'
    | '/_auth/login/'
    | '/admin/_preview/categories-preview/'
    | '/admin/_preview/dashboard-preview/'
    | '/admin/_preview/finance-preview/'
    | '/admin/_preview/integration-preview/'
    | '/admin/_preview/transaction-preview/'
    | '/admin/_protected/categories/'
    | '/admin/_protected/dashboard/'
    | '/admin/_protected/financial/'
    | '/admin/_protected/integration/'
    | '/admin/_protected/transactions/'
    | '/admin/_preview/categories-preview/category-provider/'
    | '/admin/_preview/categories-preview/category-type/'
    | '/admin/_preview/categories-preview/category/'
    | '/admin/_preview/categories-preview/server-category/'
    | '/admin/_preview/categories-preview/sub-category/'
    | '/admin/_protected/categories/category-provider/'
    | '/admin/_protected/categories/category-type/'
    | '/admin/_protected/categories/category/'
    | '/admin/_protected/categories/server-category/'
    | '/admin/_protected/categories/sub-category/'
    | '/admin/_protected/transactions/automatic/'
    | '/admin/_protected/transactions/manual/'
    | '/admin/_preview/categories-preview/category/add/'
    | '/admin/_preview/categories-preview/sub-category/add/'
    | '/admin/_preview/transaction-preview/$invoiceNo/edit/'
    | '/admin/_protected/categories/category/add/'
    | '/admin/_protected/categories/sub-category/add/'
    | '/admin/_preview/categories-preview/sub-category/$subCategoryId/edit/'
    | '/admin/_protected/categories/sub-category/$subCategoryId/edit/'
    | '/admin/_protected/transactions/automatic/$invoiceNo/edit/'
    | '/admin/_protected/transactions/manual/$invoiceNo/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminPreviewRoute: typeof AdminPreviewRouteWithChildren
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminErrorPreviewRoute: typeof AdminErrorPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/error-preview': {
      id: '/admin/error-preview'
      path: '/admin/error-preview'
      fullPath: '/admin/error-preview'
      preLoaderRoute: typeof AdminErrorPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_preview': {
      id: '/admin/_preview'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/_protected/transactions': {
      id: '/admin/_protected/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminProtectedTransactionsRouteRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/categories': {
      id: '/admin/_protected/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminProtectedCategoriesRouteRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_preview/categories-preview': {
      id: '/admin/_preview/categories-preview'
      path: '/categories-preview'
      fullPath: '/admin/categories-preview'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewRouteRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_protected/transactions/': {
      id: '/admin/_protected/transactions/'
      path: '/'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AdminProtectedTransactionsIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/integration/': {
      id: '/admin/_protected/integration/'
      path: '/integration'
      fullPath: '/admin/integration/'
      preLoaderRoute: typeof AdminProtectedIntegrationIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/financial/': {
      id: '/admin/_protected/financial/'
      path: '/financial'
      fullPath: '/admin/financial/'
      preLoaderRoute: typeof AdminProtectedFinancialIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/dashboard/': {
      id: '/admin/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminProtectedDashboardIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/categories/': {
      id: '/admin/_protected/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminProtectedCategoriesIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_preview/transaction-preview/': {
      id: '/admin/_preview/transaction-preview/'
      path: '/transaction-preview'
      fullPath: '/admin/transaction-preview/'
      preLoaderRoute: typeof AdminPreviewTransactionPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/integration-preview/': {
      id: '/admin/_preview/integration-preview/'
      path: '/integration-preview'
      fullPath: '/admin/integration-preview/'
      preLoaderRoute: typeof AdminPreviewIntegrationPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/finance-preview/': {
      id: '/admin/_preview/finance-preview/'
      path: '/finance-preview'
      fullPath: '/admin/finance-preview/'
      preLoaderRoute: typeof AdminPreviewFinancePreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/dashboard-preview/': {
      id: '/admin/_preview/dashboard-preview/'
      path: '/dashboard-preview'
      fullPath: '/admin/dashboard-preview/'
      preLoaderRoute: typeof AdminPreviewDashboardPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/categories-preview/': {
      id: '/admin/_preview/categories-preview/'
      path: '/'
      fullPath: '/admin/categories-preview/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_protected/transactions/manual/': {
      id: '/admin/_protected/transactions/manual/'
      path: '/manual'
      fullPath: '/admin/transactions/manual/'
      preLoaderRoute: typeof AdminProtectedTransactionsManualIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/transactions/automatic/': {
      id: '/admin/_protected/transactions/automatic/'
      path: '/automatic'
      fullPath: '/admin/transactions/automatic/'
      preLoaderRoute: typeof AdminProtectedTransactionsAutomaticIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/categories/sub-category/': {
      id: '/admin/_protected/categories/sub-category/'
      path: '/sub-category'
      fullPath: '/admin/categories/sub-category/'
      preLoaderRoute: typeof AdminProtectedCategoriesSubCategoryIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/server-category/': {
      id: '/admin/_protected/categories/server-category/'
      path: '/server-category'
      fullPath: '/admin/categories/server-category/'
      preLoaderRoute: typeof AdminProtectedCategoriesServerCategoryIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/category/': {
      id: '/admin/_protected/categories/category/'
      path: '/category'
      fullPath: '/admin/categories/category/'
      preLoaderRoute: typeof AdminProtectedCategoriesCategoryIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/category-type/': {
      id: '/admin/_protected/categories/category-type/'
      path: '/category-type'
      fullPath: '/admin/categories/category-type/'
      preLoaderRoute: typeof AdminProtectedCategoriesCategoryTypeIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/category-provider/': {
      id: '/admin/_protected/categories/category-provider/'
      path: '/category-provider'
      fullPath: '/admin/categories/category-provider/'
      preLoaderRoute: typeof AdminProtectedCategoriesCategoryProviderIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_preview/categories-preview/sub-category/': {
      id: '/admin/_preview/categories-preview/sub-category/'
      path: '/sub-category'
      fullPath: '/admin/categories-preview/sub-category/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewSubCategoryIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/server-category/': {
      id: '/admin/_preview/categories-preview/server-category/'
      path: '/server-category'
      fullPath: '/admin/categories-preview/server-category/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewServerCategoryIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/category/': {
      id: '/admin/_preview/categories-preview/category/'
      path: '/category'
      fullPath: '/admin/categories-preview/category/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewCategoryIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/category-type/': {
      id: '/admin/_preview/categories-preview/category-type/'
      path: '/category-type'
      fullPath: '/admin/categories-preview/category-type/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/category-provider/': {
      id: '/admin/_preview/categories-preview/category-provider/'
      path: '/category-provider'
      fullPath: '/admin/categories-preview/category-provider/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_protected/categories/sub-category/add/': {
      id: '/admin/_protected/categories/sub-category/add/'
      path: '/sub-category/add'
      fullPath: '/admin/categories/sub-category/add/'
      preLoaderRoute: typeof AdminProtectedCategoriesSubCategoryAddIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/category/add/': {
      id: '/admin/_protected/categories/category/add/'
      path: '/category/add'
      fullPath: '/admin/categories/category/add/'
      preLoaderRoute: typeof AdminProtectedCategoriesCategoryAddIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_preview/transaction-preview/$invoiceNo/edit/': {
      id: '/admin/_preview/transaction-preview/$invoiceNo/edit/'
      path: '/transaction-preview/$invoiceNo/edit'
      fullPath: '/admin/transaction-preview/$invoiceNo/edit/'
      preLoaderRoute: typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/categories-preview/sub-category/add/': {
      id: '/admin/_preview/categories-preview/sub-category/add/'
      path: '/sub-category/add'
      fullPath: '/admin/categories-preview/sub-category/add/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewSubCategoryAddIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/category/add/': {
      id: '/admin/_preview/categories-preview/category/add/'
      path: '/category/add'
      fullPath: '/admin/categories-preview/category/add/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewCategoryAddIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_protected/transactions/manual/$invoiceNo/edit/': {
      id: '/admin/_protected/transactions/manual/$invoiceNo/edit/'
      path: '/manual/$invoiceNo/edit'
      fullPath: '/admin/transactions/manual/$invoiceNo/edit/'
      preLoaderRoute: typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/transactions/automatic/$invoiceNo/edit/': {
      id: '/admin/_protected/transactions/automatic/$invoiceNo/edit/'
      path: '/automatic/$invoiceNo/edit'
      fullPath: '/admin/transactions/automatic/$invoiceNo/edit/'
      preLoaderRoute: typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/categories/sub-category/$subCategoryId/edit/': {
      id: '/admin/_protected/categories/sub-category/$subCategoryId/edit/'
      path: '/sub-category/$subCategoryId/edit'
      fullPath: '/admin/categories/sub-category/$subCategoryId/edit/'
      preLoaderRoute: typeof AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_preview/categories-preview/sub-category/$subCategoryId/edit/': {
      id: '/admin/_preview/categories-preview/sub-category/$subCategoryId/edit/'
      path: '/sub-category/$subCategoryId/edit'
      fullPath: '/admin/categories-preview/sub-category/$subCategoryId/edit/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminPreviewCategoriesPreviewRouteRouteChildren {
  AdminPreviewCategoriesPreviewIndexRoute: typeof AdminPreviewCategoriesPreviewIndexRoute
  AdminPreviewCategoriesPreviewCategoryProviderIndexRoute: typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRoute
  AdminPreviewCategoriesPreviewCategoryTypeIndexRoute: typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRoute
  AdminPreviewCategoriesPreviewCategoryIndexRoute: typeof AdminPreviewCategoriesPreviewCategoryIndexRoute
  AdminPreviewCategoriesPreviewServerCategoryIndexRoute: typeof AdminPreviewCategoriesPreviewServerCategoryIndexRoute
  AdminPreviewCategoriesPreviewSubCategoryIndexRoute: typeof AdminPreviewCategoriesPreviewSubCategoryIndexRoute
  AdminPreviewCategoriesPreviewCategoryAddIndexRoute: typeof AdminPreviewCategoriesPreviewCategoryAddIndexRoute
  AdminPreviewCategoriesPreviewSubCategoryAddIndexRoute: typeof AdminPreviewCategoriesPreviewSubCategoryAddIndexRoute
  AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRoute: typeof AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRoute
}

const AdminPreviewCategoriesPreviewRouteRouteChildren: AdminPreviewCategoriesPreviewRouteRouteChildren =
  {
    AdminPreviewCategoriesPreviewIndexRoute:
      AdminPreviewCategoriesPreviewIndexRoute,
    AdminPreviewCategoriesPreviewCategoryProviderIndexRoute:
      AdminPreviewCategoriesPreviewCategoryProviderIndexRoute,
    AdminPreviewCategoriesPreviewCategoryTypeIndexRoute:
      AdminPreviewCategoriesPreviewCategoryTypeIndexRoute,
    AdminPreviewCategoriesPreviewCategoryIndexRoute:
      AdminPreviewCategoriesPreviewCategoryIndexRoute,
    AdminPreviewCategoriesPreviewServerCategoryIndexRoute:
      AdminPreviewCategoriesPreviewServerCategoryIndexRoute,
    AdminPreviewCategoriesPreviewSubCategoryIndexRoute:
      AdminPreviewCategoriesPreviewSubCategoryIndexRoute,
    AdminPreviewCategoriesPreviewCategoryAddIndexRoute:
      AdminPreviewCategoriesPreviewCategoryAddIndexRoute,
    AdminPreviewCategoriesPreviewSubCategoryAddIndexRoute:
      AdminPreviewCategoriesPreviewSubCategoryAddIndexRoute,
    AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRoute:
      AdminPreviewCategoriesPreviewSubCategorySubCategoryIdEditIndexRoute,
  }

const AdminPreviewCategoriesPreviewRouteRouteWithChildren =
  AdminPreviewCategoriesPreviewRouteRoute._addFileChildren(
    AdminPreviewCategoriesPreviewRouteRouteChildren,
  )

interface AdminPreviewRouteChildren {
  AdminPreviewCategoriesPreviewRouteRoute: typeof AdminPreviewCategoriesPreviewRouteRouteWithChildren
  AdminPreviewDashboardPreviewIndexRoute: typeof AdminPreviewDashboardPreviewIndexRoute
  AdminPreviewFinancePreviewIndexRoute: typeof AdminPreviewFinancePreviewIndexRoute
  AdminPreviewIntegrationPreviewIndexRoute: typeof AdminPreviewIntegrationPreviewIndexRoute
  AdminPreviewTransactionPreviewIndexRoute: typeof AdminPreviewTransactionPreviewIndexRoute
  AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute: typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute
}

const AdminPreviewRouteChildren: AdminPreviewRouteChildren = {
  AdminPreviewCategoriesPreviewRouteRoute:
    AdminPreviewCategoriesPreviewRouteRouteWithChildren,
  AdminPreviewDashboardPreviewIndexRoute:
    AdminPreviewDashboardPreviewIndexRoute,
  AdminPreviewFinancePreviewIndexRoute: AdminPreviewFinancePreviewIndexRoute,
  AdminPreviewIntegrationPreviewIndexRoute:
    AdminPreviewIntegrationPreviewIndexRoute,
  AdminPreviewTransactionPreviewIndexRoute:
    AdminPreviewTransactionPreviewIndexRoute,
  AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute:
    AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute,
}

const AdminPreviewRouteWithChildren = AdminPreviewRoute._addFileChildren(
  AdminPreviewRouteChildren,
)

interface AdminProtectedCategoriesRouteRouteChildren {
  AdminProtectedCategoriesIndexRoute: typeof AdminProtectedCategoriesIndexRoute
  AdminProtectedCategoriesCategoryProviderIndexRoute: typeof AdminProtectedCategoriesCategoryProviderIndexRoute
  AdminProtectedCategoriesCategoryTypeIndexRoute: typeof AdminProtectedCategoriesCategoryTypeIndexRoute
  AdminProtectedCategoriesCategoryIndexRoute: typeof AdminProtectedCategoriesCategoryIndexRoute
  AdminProtectedCategoriesServerCategoryIndexRoute: typeof AdminProtectedCategoriesServerCategoryIndexRoute
  AdminProtectedCategoriesSubCategoryIndexRoute: typeof AdminProtectedCategoriesSubCategoryIndexRoute
  AdminProtectedCategoriesCategoryAddIndexRoute: typeof AdminProtectedCategoriesCategoryAddIndexRoute
  AdminProtectedCategoriesSubCategoryAddIndexRoute: typeof AdminProtectedCategoriesSubCategoryAddIndexRoute
  AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRoute: typeof AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRoute
}

const AdminProtectedCategoriesRouteRouteChildren: AdminProtectedCategoriesRouteRouteChildren =
  {
    AdminProtectedCategoriesIndexRoute: AdminProtectedCategoriesIndexRoute,
    AdminProtectedCategoriesCategoryProviderIndexRoute:
      AdminProtectedCategoriesCategoryProviderIndexRoute,
    AdminProtectedCategoriesCategoryTypeIndexRoute:
      AdminProtectedCategoriesCategoryTypeIndexRoute,
    AdminProtectedCategoriesCategoryIndexRoute:
      AdminProtectedCategoriesCategoryIndexRoute,
    AdminProtectedCategoriesServerCategoryIndexRoute:
      AdminProtectedCategoriesServerCategoryIndexRoute,
    AdminProtectedCategoriesSubCategoryIndexRoute:
      AdminProtectedCategoriesSubCategoryIndexRoute,
    AdminProtectedCategoriesCategoryAddIndexRoute:
      AdminProtectedCategoriesCategoryAddIndexRoute,
    AdminProtectedCategoriesSubCategoryAddIndexRoute:
      AdminProtectedCategoriesSubCategoryAddIndexRoute,
    AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRoute:
      AdminProtectedCategoriesSubCategorySubCategoryIdEditIndexRoute,
  }

const AdminProtectedCategoriesRouteRouteWithChildren =
  AdminProtectedCategoriesRouteRoute._addFileChildren(
    AdminProtectedCategoriesRouteRouteChildren,
  )

interface AdminProtectedTransactionsRouteRouteChildren {
  AdminProtectedTransactionsIndexRoute: typeof AdminProtectedTransactionsIndexRoute
  AdminProtectedTransactionsAutomaticIndexRoute: typeof AdminProtectedTransactionsAutomaticIndexRoute
  AdminProtectedTransactionsManualIndexRoute: typeof AdminProtectedTransactionsManualIndexRoute
  AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute: typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute
  AdminProtectedTransactionsManualInvoiceNoEditIndexRoute: typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRoute
}

const AdminProtectedTransactionsRouteRouteChildren: AdminProtectedTransactionsRouteRouteChildren =
  {
    AdminProtectedTransactionsIndexRoute: AdminProtectedTransactionsIndexRoute,
    AdminProtectedTransactionsAutomaticIndexRoute:
      AdminProtectedTransactionsAutomaticIndexRoute,
    AdminProtectedTransactionsManualIndexRoute:
      AdminProtectedTransactionsManualIndexRoute,
    AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute:
      AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute,
    AdminProtectedTransactionsManualInvoiceNoEditIndexRoute:
      AdminProtectedTransactionsManualInvoiceNoEditIndexRoute,
  }

const AdminProtectedTransactionsRouteRouteWithChildren =
  AdminProtectedTransactionsRouteRoute._addFileChildren(
    AdminProtectedTransactionsRouteRouteChildren,
  )

interface AdminProtectedRouteChildren {
  AdminProtectedCategoriesRouteRoute: typeof AdminProtectedCategoriesRouteRouteWithChildren
  AdminProtectedTransactionsRouteRoute: typeof AdminProtectedTransactionsRouteRouteWithChildren
  AdminProtectedDashboardIndexRoute: typeof AdminProtectedDashboardIndexRoute
  AdminProtectedFinancialIndexRoute: typeof AdminProtectedFinancialIndexRoute
  AdminProtectedIntegrationIndexRoute: typeof AdminProtectedIntegrationIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedCategoriesRouteRoute:
    AdminProtectedCategoriesRouteRouteWithChildren,
  AdminProtectedTransactionsRouteRoute:
    AdminProtectedTransactionsRouteRouteWithChildren,
  AdminProtectedDashboardIndexRoute: AdminProtectedDashboardIndexRoute,
  AdminProtectedFinancialIndexRoute: AdminProtectedFinancialIndexRoute,
  AdminProtectedIntegrationIndexRoute: AdminProtectedIntegrationIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminPreviewRoute: AdminPreviewRouteWithChildren,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminErrorPreviewRoute: AdminErrorPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
