<?php

/*
|--------------------------------------------------------------------------
| Monetapay disbursement / payout catalogue
|--------------------------------------------------------------------------
| Canonical `account_bank_code` values accepted by Monetapay payouts. Used to
| validate the merchant withdrawal `bank_code` and to route the payout:
|   - codes in `ewallet_codes` → Monetapay e-wallet payout (createEwalletPayout,
|     keyed on the recipient phone, no account number)
|   - everything else → bank disbursement (createDisbursement, needs account number)
|
| Mirror of web-payment-fe `src/features/merchant/constants/bankCodes.ts` — keep
| the two in sync. Deduped by code from the official Monetapay bank-code list.
*/

return [

    // E-wallet destinations (payout via /v1.0.0/ewallet-disbursement).
    'ewallet_codes' => ['OVO', 'DANA', 'LINKAJA', 'SHOPEEPAY', 'GOPAY'],

    // code => display name.
    'list' => [
        'ANGLOMAS' => 'Anglomas International Bank',
        'BANGKOK' => 'Bangkok Bank',
        'AGRIS' => 'Bank Agris',
        'AGRONIAGA' => 'Bank Agroniaga',
        'AMAR' => 'Bank Amar Indonesia',
        'ANDARA' => 'Bank Andara',
        'ANZ' => 'Bank ANZ Indonesia',
        'ARTA_NIAGA_KENCANA' => 'Bank Arta Niaga Kencana',
        'ARTHA' => 'Bank Artha Graha International',
        'ARTOS' => 'Bank Artos Indonesia',
        'BISNIS_INTERNASIONAL' => 'Bank Bisnis Internasional',
        'BJB' => 'Bank BJB',
        'BJB_SYR' => 'Bank BJB Syariah',
        'BNI_SYR' => 'Bank BNI Syariah',
        'BNP_PARIBAS' => 'Bank BNP Paribas',
        'BUKOPIN' => 'Bank Bukopin',
        'BUMI_ARTA' => 'Bank Bumi Arta',
        'CAPITAL' => 'Bank Capital Indonesia',
        'BCA' => 'Bank Central Asia (BCA)',
        'BCA_SYR' => 'Bank Central Asia (BCA) Syariah',
        'CHINATRUST' => 'Bank Chinatrust Indonesia',
        'CIMB' => 'Bank CIMB Niaga',
        'CIMB_UUS' => 'Bank CIMB Niaga UUS',
        'COMMONWEALTH' => 'Bank Commonwealth',
        'DANAMON' => 'Bank Danamon',
        'DANAMON_UUS' => 'Bank Danamon UUS',
        'DBS' => 'Bank DBS Indonesia',
        'DINAR_INDONESIA' => 'Bank Dinar Indonesia',
        'DKI' => 'Bank DKI',
        'DKI_UUS' => 'Bank DKI UUS',
        'FAMA' => 'Bank Fama International',
        'GANESHA' => 'Bank Ganesha',
        'HANA' => 'Bank Hana',
        'HARDA_INTERNASIONAL' => 'Bank Harda Internasional',
        'HIMPUNAN_SAUDARA' => 'Bank Himpunan Saudara 1906',
        'ICBC' => 'Bank ICBC Indonesia',
        'INA_PERDANA' => 'Bank Ina Perdania',
        'INDEX_SELINDO' => 'Bank Index Selindo',
        'JASA_JAKARTA' => 'Bank Jasa Jakarta',
        'JTRUST' => 'Bank JTrust Indonesia',
        'KESEJAHTERAAN_EKONOMI' => 'Bank Kesejahteraan Ekonomi',
        'MANDIRI' => 'Bank Mandiri',
        'MASPION' => 'Bank Maspion Indonesia',
        'MAYAPADA' => 'Bank Mayapada International',
        'MAYBANK' => 'Bank Maybank',
        'MAYBANK_SYR' => 'Bank Maybank Syariah Indonesia',
        'MAYORA' => 'Bank Mayora',
        'MEGA' => 'Bank Mega',
        'MESTIKA_DHARMA' => 'Bank Mestika Dharma',
        'MITRA_NIAGA' => 'Bank Mitra Niaga',
        'MIZUHO' => 'Bank Mizuho Indonesia',
        'MNC_INTERNASIONAL' => 'Bank MNC Internasional',
        'MUAMALAT' => 'Bank Muamalat Indonesia',
        'MULTI_ARTA_SENTOSA' => 'Bank Multi Arta Sentosa',
        'NATIONALNOBU' => 'Bank Nationalnobu',
        'BNI' => 'Bank Negara Indonesia (BNI)',
        'NUSANTARA_PARAHYANGAN' => 'Bank Nusantara Parahyangan',
        'OCBC' => 'Bank OCBC NISP',
        'OCBC_UUS' => 'Bank OCBC NISP UUS',
        'BAML' => 'Bank of America Merill-Lynch',
        'BOC' => 'Bank of China (BOC)',
        'INDIA' => 'Bank of India Indonesia',
        'TOKYO' => 'Bank of Tokyo Mitsubishi UFJ',
        'OKE' => 'Bank Oke Indonesia',
        'PANIN' => 'Bank Panin',
        'PANIN_SYR' => 'Bank Panin Syariah',
        'PERMATA' => 'Bank Permata',
        'PERMATA_UUS' => 'Bank Permata UUS',
        'QNB_INDONESIA' => 'Bank QNB Indonesia',
        'RABOBANK' => 'Bank Rabobank International Indonesia',
        'BRI' => 'Bank Rakyat Indonesia (BRI)',
        'RESONA' => 'Bank Resona Perdania',
        'ROYAL' => 'Bank Royal Indonesia',
        'SAHABAT_SAMPOERNA' => 'Bank Sahabat Sampoerna',
        'SBI_INDONESIA' => 'Bank SBI Indonesia',
        'SHINHAN' => 'Bank Shinhan Indonesia',
        'SINARMAS' => 'Bank Sinarmas',
        'SINARMAS_UUS' => 'Bank Sinarmas UUS',
        'MITSUI' => 'Bank Sumitomo Mitsui Indonesia',
        'BRI_SYR' => 'Bank Syariah BRI',
        'BUKOPIN_SYR' => 'Bank Syariah Bukopin',
        'MANDIRI_SYR' => 'Bank Syariah Mandiri',
        'MEGA_SYR' => 'Bank Syariah Mega',
        'BTN' => 'Bank Tabungan Negara (BTN)',
        'BTN_UUS' => 'Bank Tabungan Negara (BTN) UUS',
        'TABUNGAN_PENSIUNAN_NASIONAL' => 'Bank Tabungan Pensiunan Nasional',
        'BTPN' => 'Bank Tabungan Pensiunan Nasional (BTPN)',
        'UOB' => 'Bank UOB Indonesia',
        'VICTORIA_INTERNASIONAL' => 'Bank Victoria Internasional',
        'VICTORIA_SYR' => 'Bank Victoria Syariah',
        'WOORI' => 'Bank Woori Indonesia',
        'WOORI_SAUDARA' => 'Bank Woori Saudara Indonesia 1906',
        'YUDHA_BHAKTI' => 'Bank Yudha Bhakti',
        'ACEH' => 'BPD Aceh',
        'ACEH_UUS' => 'BPD Aceh UUS',
        'BANTEN' => 'BPD Banten',
        'BENGKULU' => 'BPD Bengkulu',
        'DAERAH_ISTIMEWA_UUS' => 'BPD Daerah Istimewa Yogyakarta (DIY) UUS',
        'JAMBI' => 'BPD Jambi',
        'JAMBI_UUS' => 'BPD Jambi UUS',
        'JAWA_TENGAH' => 'BPD Jawa Tengah',
        'JAWA_TENGAH_UUS' => 'BPD Jawa Tengah UUS',
        'JAWA_TIMUR' => 'BPD Jawa Timur',
        'JAWA_TIMUR_UUS' => 'BPD Jawa Timur UUS',
        'KALIMANTAN_BARAT' => 'BPD Kalimantan Barat',
        'KALIMANTAN_BARAT_UUS' => 'BPD Kalimantan Barat UUS',
        'KALIMANTAN_SELATAN' => 'BPD Kalimantan Selatan',
        'KALIMANTAN_SELATAN_UUS' => 'BPD Kalimantan Selatan UUS',
        'KALIMANTAN_TENGAH' => 'BPD Kalimantan Tengah',
        'KALIMANTAN_TIMUR' => 'BPD Kalimantan Timur',
        'KALIMANTAN_TIMUR_UUS' => 'BPD Kalimantan Timur UUS',
        'LAMPUNG' => 'BPD Lampung',
        'MALUKU' => 'BPD Maluku',
        'NUSA_TENGGARA_BARAT' => 'BPD Nusa Tenggara Barat',
        'NUSA_TENGGARA_BARAT_UUS' => 'BPD Nusa Tenggara Barat UUS',
        'NUSA_TENGGARA_TIMUR' => 'BPD Nusa Tenggara Timur',
        'PAPUA' => 'BPD Papua',
        'RIAU_DAN_KEPRI' => 'BPD Riau Dan Kepri',
        'RIAU_DAN_KEPRI_UUS' => 'BPD Riau Dan Kepri UUS',
        'SULAWESI' => 'BPD Sulawesi Tengah',
        'SULAWESI_TENGGARA' => 'BPD Sulawesi Tenggara',
        'SULSELBAR' => 'BPD Sulselbar',
        'SULSELBAR_UUS' => 'BPD Sulselbar UUS',
        'SULUT' => 'BPD Sulut',
        'SUMATERA_BARAT' => 'BPD Sumatera Barat',
        'SUMATERA_BARAT_UUS' => 'BPD Sumatera Barat UUS',
        'SUMSEL_DAN_BABEL' => 'BPD Sumsel Dan Babel',
        'SUMSEL_DAN_BABEL_UUS' => 'BPD Sumsel Dan Babel UUS',
        'SUMUT' => 'BPD Sumut',
        'SUMUT_UUS' => 'BPD Sumut UUS',
        'BTPN_SYARIAH' => 'BTPN Syariah',
        'CENTRATAMA' => 'Centratama Nasional Bank',
        'CCB' => 'China Construction Bank Indonesia',
        'CITIBANK' => 'Citibank',
        'DEUTSCHE' => 'Deutsche Bank',
        'HSBC_UUS' => 'HSBC UUS',
        'HSBC' => 'HSBC Indonesia',
        'EXIMBANK' => 'Indonesia Eximbank',
        'JPMORGAN' => 'JP Morgan Chase Bank',
        'MANDIRI_TASPEN' => 'Mandiri Taspen Pos',
        'PRIMA_MASTER' => 'Prima Master Bank',
        'RBS' => 'Royal Bank of Scotland (RBS)',
        'STANDARD_CHARTERED' => 'Standard Chartered Bank',
        'BSI' => 'Bank Syariah Indonesia (BSI)',
        'BNC' => 'Bank Neo Commerce',
        'SEABANK' => 'Bank Seabank Indonesia',
        'BSS' => 'Bank Sahabat Sampoerna (BSS)',
        'ALLO' => 'Allo Bank Indonesia',
        'JAGO' => 'Bank Jago',
        'IBK' => 'Bank IBK Indonesia',
        'ALADIN' => 'Bank Aladin Syariah',
        'BALI' => 'BPD Bali',
        'BCA_DIGITAL' => 'Bank Digital BCA',
        'JAGO_UUS' => 'Bank Jago UUS',
        'CTBC' => 'Bank CTBC Indonesia',
        'NAGARI' => 'Bank Nagari',
        'NAGARI_UUS' => 'Bank Nagari UUS',
        'DIY_UUS' => 'BPD DIY UUS',
        'JABAR_BANTEN_SYR' => 'Bank Jabar Banten Syariah',
        'AGI' => 'Bank Artha Graha Internasional',
        'RAYA' => 'Bank Raya Indonesia',
        'BI' => 'Bank Indonesia',
        'KSEI' => 'PT. KSEI',
        'NTT' => 'BPD NTT',
        'DAERAH_ISTIMEWA' => 'BPD Daerah Istimewa Yogyakarta (DIY)',

        // E-wallets (payout via e-wallet disbursement — see ewallet_codes above).
        'OVO' => 'OVO',
        'DANA' => 'DANA',
        'LINKAJA' => 'LinkAja',
        'SHOPEEPAY' => 'ShopeePay',
        'GOPAY' => 'GoPay',
    ],
];
