[program:laravel-queue-staging]
process_name=%(program_name)s_%(process_num)02d
command=php /home/uxioserver1/web-topup/api/staging/artisan queue:work database --sleep=3 --tries=3 --timeout=90 --max-jobs=500 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=uxioserver1
numprocs=1
redirect_stderr=true
stdout_logfile=/home/uxioserver1/web-topup/api/staging/storage/logs/worker.log
stopwaitsecs=3600
