[program:laravel-queue-prod]
process_name=%(program_name)s_%(process_num)02d
command=php /home/dreamy-8/web-topup/api/prod/artisan queue:work database --sleep=3 --tries=3 --timeout=90 --max-jobs=500 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=dreamy-8
numprocs=1
redirect_stderr=true
stdout_logfile=/home/dreamy-8/web-topup/api/prod/storage/logs/worker.log
stopwaitsecs=3600
