[program:laravel-reverb-prod]
process_name=%(program_name)s_%(process_num)02d
command=php /home/uxioserver1/web-topup/api/prod/artisan reverb:start --host=0.0.0.0 --port=8080
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=uxioserver1
numprocs=1
redirect_stderr=true
stdout_logfile=/home/uxioserver1/web-topup/api/prod/storage/logs/reverb.log
stopwaitsecs=10
