/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProtectedRouteImport } from './routes/app/_protected'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AppProtectedWithdrawalsIndexRouteImport } from './routes/app/_protected/withdrawals/index'
import { Route as AppProtectedTransactionsIndexRouteImport } from './routes/app/_protected/transactions/index'
import { Route as AppProtectedMutationsIndexRouteImport } from './routes/app/_protected/mutations/index'
import { Route as AppProtectedDashboardIndexRouteImport } from './routes/app/_protected/dashboard/index'
import { Route as AppProtectedFinanceWithdrawalsIndexRouteImport } from './routes/app/_protected/finance/withdrawals/index'
import { Route as AppProtectedFinanceTransactionsIndexRouteImport } from './routes/app/_protected/finance/transactions/index'
import { Route as AppProtectedFinanceMerchantsIndexRouteImport } from './routes/app/_protected/finance/merchants/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/app/_protected',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppProtectedWithdrawalsIndexRoute =
  AppProtectedWithdrawalsIndexRouteImport.update({
    id: '/withdrawals/',
    path: '/withdrawals/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedTransactionsIndexRoute =
  AppProtectedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedMutationsIndexRoute =
  AppProtectedMutationsIndexRouteImport.update({
    id: '/mutations/',
    path: '/mutations/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedDashboardIndexRoute =
  AppProtectedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedFinanceWithdrawalsIndexRoute =
  AppProtectedFinanceWithdrawalsIndexRouteImport.update({
    id: '/finance/withdrawals/',
    path: '/finance/withdrawals/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedFinanceTransactionsIndexRoute =
  AppProtectedFinanceTransactionsIndexRouteImport.update({
    id: '/finance/transactions/',
    path: '/finance/transactions/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedFinanceMerchantsIndexRoute =
  AppProtectedFinanceMerchantsIndexRouteImport.update({
    id: '/finance/merchants/',
    path: '/finance/merchants/',
    getParentRoute: () => AppProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppProtectedRouteWithChildren
  '/login/': typeof AuthLoginIndexRoute
  '/app/dashboard/': typeof AppProtectedDashboardIndexRoute
  '/app/mutations/': typeof AppProtectedMutationsIndexRoute
  '/app/transactions/': typeof AppProtectedTransactionsIndexRoute
  '/app/withdrawals/': typeof AppProtectedWithdrawalsIndexRoute
  '/app/finance/merchants/': typeof AppProtectedFinanceMerchantsIndexRoute
  '/app/finance/transactions/': typeof AppProtectedFinanceTransactionsIndexRoute
  '/app/finance/withdrawals/': typeof AppProtectedFinanceWithdrawalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppProtectedRouteWithChildren
  '/login': typeof AuthLoginIndexRoute
  '/app/dashboard': typeof AppProtectedDashboardIndexRoute
  '/app/mutations': typeof AppProtectedMutationsIndexRoute
  '/app/transactions': typeof AppProtectedTransactionsIndexRoute
  '/app/withdrawals': typeof AppProtectedWithdrawalsIndexRoute
  '/app/finance/merchants': typeof AppProtectedFinanceMerchantsIndexRoute
  '/app/finance/transactions': typeof AppProtectedFinanceTransactionsIndexRoute
  '/app/finance/withdrawals': typeof AppProtectedFinanceWithdrawalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app/_protected': typeof AppProtectedRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/app/_protected/dashboard/': typeof AppProtectedDashboardIndexRoute
  '/app/_protected/mutations/': typeof AppProtectedMutationsIndexRoute
  '/app/_protected/transactions/': typeof AppProtectedTransactionsIndexRoute
  '/app/_protected/withdrawals/': typeof AppProtectedWithdrawalsIndexRoute
  '/app/_protected/finance/merchants/': typeof AppProtectedFinanceMerchantsIndexRoute
  '/app/_protected/finance/transactions/': typeof AppProtectedFinanceTransactionsIndexRoute
  '/app/_protected/finance/withdrawals/': typeof AppProtectedFinanceWithdrawalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login/'
    | '/app/dashboard/'
    | '/app/mutations/'
    | '/app/transactions/'
    | '/app/withdrawals/'
    | '/app/finance/merchants/'
    | '/app/finance/transactions/'
    | '/app/finance/withdrawals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/mutations'
    | '/app/transactions'
    | '/app/withdrawals'
    | '/app/finance/merchants'
    | '/app/finance/transactions'
    | '/app/finance/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app/_protected'
    | '/_auth/login/'
    | '/app/_protected/dashboard/'
    | '/app/_protected/mutations/'
    | '/app/_protected/transactions/'
    | '/app/_protected/withdrawals/'
    | '/app/_protected/finance/merchants/'
    | '/app/_protected/finance/transactions/'
    | '/app/_protected/finance/withdrawals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppProtectedRoute: typeof AppProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_protected': {
      id: '/app/_protected'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/_protected/withdrawals/': {
      id: '/app/_protected/withdrawals/'
      path: '/withdrawals'
      fullPath: '/app/withdrawals/'
      preLoaderRoute: typeof AppProtectedWithdrawalsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/transactions/': {
      id: '/app/_protected/transactions/'
      path: '/transactions'
      fullPath: '/app/transactions/'
      preLoaderRoute: typeof AppProtectedTransactionsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/mutations/': {
      id: '/app/_protected/mutations/'
      path: '/mutations'
      fullPath: '/app/mutations/'
      preLoaderRoute: typeof AppProtectedMutationsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/dashboard/': {
      id: '/app/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppProtectedDashboardIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/finance/withdrawals/': {
      id: '/app/_protected/finance/withdrawals/'
      path: '/finance/withdrawals'
      fullPath: '/app/finance/withdrawals/'
      preLoaderRoute: typeof AppProtectedFinanceWithdrawalsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/finance/transactions/': {
      id: '/app/_protected/finance/transactions/'
      path: '/finance/transactions'
      fullPath: '/app/finance/transactions/'
      preLoaderRoute: typeof AppProtectedFinanceTransactionsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/finance/merchants/': {
      id: '/app/_protected/finance/merchants/'
      path: '/finance/merchants'
      fullPath: '/app/finance/merchants/'
      preLoaderRoute: typeof AppProtectedFinanceMerchantsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppProtectedRouteChildren {
  AppProtectedDashboardIndexRoute: typeof AppProtectedDashboardIndexRoute
  AppProtectedMutationsIndexRoute: typeof AppProtectedMutationsIndexRoute
  AppProtectedTransactionsIndexRoute: typeof AppProtectedTransactionsIndexRoute
  AppProtectedWithdrawalsIndexRoute: typeof AppProtectedWithdrawalsIndexRoute
  AppProtectedFinanceMerchantsIndexRoute: typeof AppProtectedFinanceMerchantsIndexRoute
  AppProtectedFinanceTransactionsIndexRoute: typeof AppProtectedFinanceTransactionsIndexRoute
  AppProtectedFinanceWithdrawalsIndexRoute: typeof AppProtectedFinanceWithdrawalsIndexRoute
}

const AppProtectedRouteChildren: AppProtectedRouteChildren = {
  AppProtectedDashboardIndexRoute: AppProtectedDashboardIndexRoute,
  AppProtectedMutationsIndexRoute: AppProtectedMutationsIndexRoute,
  AppProtectedTransactionsIndexRoute: AppProtectedTransactionsIndexRoute,
  AppProtectedWithdrawalsIndexRoute: AppProtectedWithdrawalsIndexRoute,
  AppProtectedFinanceMerchantsIndexRoute:
    AppProtectedFinanceMerchantsIndexRoute,
  AppProtectedFinanceTransactionsIndexRoute:
    AppProtectedFinanceTransactionsIndexRoute,
  AppProtectedFinanceWithdrawalsIndexRoute:
    AppProtectedFinanceWithdrawalsIndexRoute,
}

const AppProtectedRouteWithChildren = AppProtectedRoute._addFileChildren(
  AppProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppProtectedRoute: AppProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
