/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProtectedRouteImport } from './routes/app/_protected'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AppProtectedDashboardIndexRouteImport } from './routes/app/_protected/dashboard/index'
import { Route as AppProtectedPaymentInternalWithdrawalsIndexRouteImport } from './routes/app/_protected/payment-internal/withdrawals/index'
import { Route as AppProtectedPaymentInternalTransactionsIndexRouteImport } from './routes/app/_protected/payment-internal/transactions/index'
import { Route as AppProtectedPaymentInternalSubscriptionsIndexRouteImport } from './routes/app/_protected/payment-internal/subscriptions/index'
import { Route as AppProtectedPaymentInternalServicesIndexRouteImport } from './routes/app/_protected/payment-internal/services/index'
import { Route as AppProtectedPaymentInternalNotificationsIndexRouteImport } from './routes/app/_protected/payment-internal/notifications/index'
import { Route as AppProtectedPaymentInternalMerchantsIndexRouteImport } from './routes/app/_protected/payment-internal/merchants/index'
import { Route as AppProtectedPaymentInternalInvoicesIndexRouteImport } from './routes/app/_protected/payment-internal/invoices/index'
import { Route as AppProtectedPaymentInternalIncidentsIndexRouteImport } from './routes/app/_protected/payment-internal/incidents/index'
import { Route as AppProtectedPaymentInternalChannelsIndexRouteImport } from './routes/app/_protected/payment-internal/channels/index'
import { Route as AppProtectedPaymentAdminWithdrawalsIndexRouteImport } from './routes/app/_protected/payment-admin/withdrawals/index'
import { Route as AppProtectedPaymentAdminTransactionsIndexRouteImport } from './routes/app/_protected/payment-admin/transactions/index'
import { Route as AppProtectedPaymentAdminServicesIndexRouteImport } from './routes/app/_protected/payment-admin/services/index'
import { Route as AppProtectedPaymentAdminServiceStatusIndexRouteImport } from './routes/app/_protected/payment-admin/service-status/index'
import { Route as AppProtectedPaymentAdminMutationsIndexRouteImport } from './routes/app/_protected/payment-admin/mutations/index'
import { Route as AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRouteImport } from './routes/app/_protected/payment-internal/subscriptions/$subscriptionId/index'
import { Route as AppProtectedPaymentInternalInvoicesInvoiceIdIndexRouteImport } from './routes/app/_protected/payment-internal/invoices/$invoiceId/index'
import { Route as AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRouteImport } from './routes/app/_protected/payment-admin/service-invoices/$invoiceId/index'
import { Route as AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRouteImport } from './routes/app/_protected/payment-admin/services/$serviceId/checkout/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/app/_protected',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppProtectedDashboardIndexRoute =
  AppProtectedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalWithdrawalsIndexRoute =
  AppProtectedPaymentInternalWithdrawalsIndexRouteImport.update({
    id: '/payment-internal/withdrawals/',
    path: '/payment-internal/withdrawals/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalTransactionsIndexRoute =
  AppProtectedPaymentInternalTransactionsIndexRouteImport.update({
    id: '/payment-internal/transactions/',
    path: '/payment-internal/transactions/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalSubscriptionsIndexRoute =
  AppProtectedPaymentInternalSubscriptionsIndexRouteImport.update({
    id: '/payment-internal/subscriptions/',
    path: '/payment-internal/subscriptions/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalServicesIndexRoute =
  AppProtectedPaymentInternalServicesIndexRouteImport.update({
    id: '/payment-internal/services/',
    path: '/payment-internal/services/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalNotificationsIndexRoute =
  AppProtectedPaymentInternalNotificationsIndexRouteImport.update({
    id: '/payment-internal/notifications/',
    path: '/payment-internal/notifications/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalMerchantsIndexRoute =
  AppProtectedPaymentInternalMerchantsIndexRouteImport.update({
    id: '/payment-internal/merchants/',
    path: '/payment-internal/merchants/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalInvoicesIndexRoute =
  AppProtectedPaymentInternalInvoicesIndexRouteImport.update({
    id: '/payment-internal/invoices/',
    path: '/payment-internal/invoices/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalIncidentsIndexRoute =
  AppProtectedPaymentInternalIncidentsIndexRouteImport.update({
    id: '/payment-internal/incidents/',
    path: '/payment-internal/incidents/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalChannelsIndexRoute =
  AppProtectedPaymentInternalChannelsIndexRouteImport.update({
    id: '/payment-internal/channels/',
    path: '/payment-internal/channels/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminWithdrawalsIndexRoute =
  AppProtectedPaymentAdminWithdrawalsIndexRouteImport.update({
    id: '/payment-admin/withdrawals/',
    path: '/payment-admin/withdrawals/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminTransactionsIndexRoute =
  AppProtectedPaymentAdminTransactionsIndexRouteImport.update({
    id: '/payment-admin/transactions/',
    path: '/payment-admin/transactions/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminServicesIndexRoute =
  AppProtectedPaymentAdminServicesIndexRouteImport.update({
    id: '/payment-admin/services/',
    path: '/payment-admin/services/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminServiceStatusIndexRoute =
  AppProtectedPaymentAdminServiceStatusIndexRouteImport.update({
    id: '/payment-admin/service-status/',
    path: '/payment-admin/service-status/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminMutationsIndexRoute =
  AppProtectedPaymentAdminMutationsIndexRouteImport.update({
    id: '/payment-admin/mutations/',
    path: '/payment-admin/mutations/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRoute =
  AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRouteImport.update(
    {
      id: '/payment-internal/subscriptions/$subscriptionId/',
      path: '/payment-internal/subscriptions/$subscriptionId/',
      getParentRoute: () => AppProtectedRoute,
    } as any,
  )
const AppProtectedPaymentInternalInvoicesInvoiceIdIndexRoute =
  AppProtectedPaymentInternalInvoicesInvoiceIdIndexRouteImport.update({
    id: '/payment-internal/invoices/$invoiceId/',
    path: '/payment-internal/invoices/$invoiceId/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRoute =
  AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRouteImport.update({
    id: '/payment-admin/service-invoices/$invoiceId/',
    path: '/payment-admin/service-invoices/$invoiceId/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRoute =
  AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRouteImport.update({
    id: '/payment-admin/services/$serviceId/checkout/',
    path: '/payment-admin/services/$serviceId/checkout/',
    getParentRoute: () => AppProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppProtectedRouteWithChildren
  '/login/': typeof AuthLoginIndexRoute
  '/app/dashboard/': typeof AppProtectedDashboardIndexRoute
  '/app/payment-admin/mutations/': typeof AppProtectedPaymentAdminMutationsIndexRoute
  '/app/payment-admin/service-status/': typeof AppProtectedPaymentAdminServiceStatusIndexRoute
  '/app/payment-admin/services/': typeof AppProtectedPaymentAdminServicesIndexRoute
  '/app/payment-admin/transactions/': typeof AppProtectedPaymentAdminTransactionsIndexRoute
  '/app/payment-admin/withdrawals/': typeof AppProtectedPaymentAdminWithdrawalsIndexRoute
  '/app/payment-internal/channels/': typeof AppProtectedPaymentInternalChannelsIndexRoute
  '/app/payment-internal/incidents/': typeof AppProtectedPaymentInternalIncidentsIndexRoute
  '/app/payment-internal/invoices/': typeof AppProtectedPaymentInternalInvoicesIndexRoute
  '/app/payment-internal/merchants/': typeof AppProtectedPaymentInternalMerchantsIndexRoute
  '/app/payment-internal/notifications/': typeof AppProtectedPaymentInternalNotificationsIndexRoute
  '/app/payment-internal/services/': typeof AppProtectedPaymentInternalServicesIndexRoute
  '/app/payment-internal/subscriptions/': typeof AppProtectedPaymentInternalSubscriptionsIndexRoute
  '/app/payment-internal/transactions/': typeof AppProtectedPaymentInternalTransactionsIndexRoute
  '/app/payment-internal/withdrawals/': typeof AppProtectedPaymentInternalWithdrawalsIndexRoute
  '/app/payment-admin/service-invoices/$invoiceId/': typeof AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRoute
  '/app/payment-internal/invoices/$invoiceId/': typeof AppProtectedPaymentInternalInvoicesInvoiceIdIndexRoute
  '/app/payment-internal/subscriptions/$subscriptionId/': typeof AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRoute
  '/app/payment-admin/services/$serviceId/checkout/': typeof AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppProtectedRouteWithChildren
  '/login': typeof AuthLoginIndexRoute
  '/app/dashboard': typeof AppProtectedDashboardIndexRoute
  '/app/payment-admin/mutations': typeof AppProtectedPaymentAdminMutationsIndexRoute
  '/app/payment-admin/service-status': typeof AppProtectedPaymentAdminServiceStatusIndexRoute
  '/app/payment-admin/services': typeof AppProtectedPaymentAdminServicesIndexRoute
  '/app/payment-admin/transactions': typeof AppProtectedPaymentAdminTransactionsIndexRoute
  '/app/payment-admin/withdrawals': typeof AppProtectedPaymentAdminWithdrawalsIndexRoute
  '/app/payment-internal/channels': typeof AppProtectedPaymentInternalChannelsIndexRoute
  '/app/payment-internal/incidents': typeof AppProtectedPaymentInternalIncidentsIndexRoute
  '/app/payment-internal/invoices': typeof AppProtectedPaymentInternalInvoicesIndexRoute
  '/app/payment-internal/merchants': typeof AppProtectedPaymentInternalMerchantsIndexRoute
  '/app/payment-internal/notifications': typeof AppProtectedPaymentInternalNotificationsIndexRoute
  '/app/payment-internal/services': typeof AppProtectedPaymentInternalServicesIndexRoute
  '/app/payment-internal/subscriptions': typeof AppProtectedPaymentInternalSubscriptionsIndexRoute
  '/app/payment-internal/transactions': typeof AppProtectedPaymentInternalTransactionsIndexRoute
  '/app/payment-internal/withdrawals': typeof AppProtectedPaymentInternalWithdrawalsIndexRoute
  '/app/payment-admin/service-invoices/$invoiceId': typeof AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRoute
  '/app/payment-internal/invoices/$invoiceId': typeof AppProtectedPaymentInternalInvoicesInvoiceIdIndexRoute
  '/app/payment-internal/subscriptions/$subscriptionId': typeof AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRoute
  '/app/payment-admin/services/$serviceId/checkout': typeof AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app/_protected': typeof AppProtectedRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/app/_protected/dashboard/': typeof AppProtectedDashboardIndexRoute
  '/app/_protected/payment-admin/mutations/': typeof AppProtectedPaymentAdminMutationsIndexRoute
  '/app/_protected/payment-admin/service-status/': typeof AppProtectedPaymentAdminServiceStatusIndexRoute
  '/app/_protected/payment-admin/services/': typeof AppProtectedPaymentAdminServicesIndexRoute
  '/app/_protected/payment-admin/transactions/': typeof AppProtectedPaymentAdminTransactionsIndexRoute
  '/app/_protected/payment-admin/withdrawals/': typeof AppProtectedPaymentAdminWithdrawalsIndexRoute
  '/app/_protected/payment-internal/channels/': typeof AppProtectedPaymentInternalChannelsIndexRoute
  '/app/_protected/payment-internal/incidents/': typeof AppProtectedPaymentInternalIncidentsIndexRoute
  '/app/_protected/payment-internal/invoices/': typeof AppProtectedPaymentInternalInvoicesIndexRoute
  '/app/_protected/payment-internal/merchants/': typeof AppProtectedPaymentInternalMerchantsIndexRoute
  '/app/_protected/payment-internal/notifications/': typeof AppProtectedPaymentInternalNotificationsIndexRoute
  '/app/_protected/payment-internal/services/': typeof AppProtectedPaymentInternalServicesIndexRoute
  '/app/_protected/payment-internal/subscriptions/': typeof AppProtectedPaymentInternalSubscriptionsIndexRoute
  '/app/_protected/payment-internal/transactions/': typeof AppProtectedPaymentInternalTransactionsIndexRoute
  '/app/_protected/payment-internal/withdrawals/': typeof AppProtectedPaymentInternalWithdrawalsIndexRoute
  '/app/_protected/payment-admin/service-invoices/$invoiceId/': typeof AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRoute
  '/app/_protected/payment-internal/invoices/$invoiceId/': typeof AppProtectedPaymentInternalInvoicesInvoiceIdIndexRoute
  '/app/_protected/payment-internal/subscriptions/$subscriptionId/': typeof AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRoute
  '/app/_protected/payment-admin/services/$serviceId/checkout/': typeof AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login/'
    | '/app/dashboard/'
    | '/app/payment-admin/mutations/'
    | '/app/payment-admin/service-status/'
    | '/app/payment-admin/services/'
    | '/app/payment-admin/transactions/'
    | '/app/payment-admin/withdrawals/'
    | '/app/payment-internal/channels/'
    | '/app/payment-internal/incidents/'
    | '/app/payment-internal/invoices/'
    | '/app/payment-internal/merchants/'
    | '/app/payment-internal/notifications/'
    | '/app/payment-internal/services/'
    | '/app/payment-internal/subscriptions/'
    | '/app/payment-internal/transactions/'
    | '/app/payment-internal/withdrawals/'
    | '/app/payment-admin/service-invoices/$invoiceId/'
    | '/app/payment-internal/invoices/$invoiceId/'
    | '/app/payment-internal/subscriptions/$subscriptionId/'
    | '/app/payment-admin/services/$serviceId/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/payment-admin/mutations'
    | '/app/payment-admin/service-status'
    | '/app/payment-admin/services'
    | '/app/payment-admin/transactions'
    | '/app/payment-admin/withdrawals'
    | '/app/payment-internal/channels'
    | '/app/payment-internal/incidents'
    | '/app/payment-internal/invoices'
    | '/app/payment-internal/merchants'
    | '/app/payment-internal/notifications'
    | '/app/payment-internal/services'
    | '/app/payment-internal/subscriptions'
    | '/app/payment-internal/transactions'
    | '/app/payment-internal/withdrawals'
    | '/app/payment-admin/service-invoices/$invoiceId'
    | '/app/payment-internal/invoices/$invoiceId'
    | '/app/payment-internal/subscriptions/$subscriptionId'
    | '/app/payment-admin/services/$serviceId/checkout'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app/_protected'
    | '/_auth/login/'
    | '/app/_protected/dashboard/'
    | '/app/_protected/payment-admin/mutations/'
    | '/app/_protected/payment-admin/service-status/'
    | '/app/_protected/payment-admin/services/'
    | '/app/_protected/payment-admin/transactions/'
    | '/app/_protected/payment-admin/withdrawals/'
    | '/app/_protected/payment-internal/channels/'
    | '/app/_protected/payment-internal/incidents/'
    | '/app/_protected/payment-internal/invoices/'
    | '/app/_protected/payment-internal/merchants/'
    | '/app/_protected/payment-internal/notifications/'
    | '/app/_protected/payment-internal/services/'
    | '/app/_protected/payment-internal/subscriptions/'
    | '/app/_protected/payment-internal/transactions/'
    | '/app/_protected/payment-internal/withdrawals/'
    | '/app/_protected/payment-admin/service-invoices/$invoiceId/'
    | '/app/_protected/payment-internal/invoices/$invoiceId/'
    | '/app/_protected/payment-internal/subscriptions/$subscriptionId/'
    | '/app/_protected/payment-admin/services/$serviceId/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppProtectedRoute: typeof AppProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_protected': {
      id: '/app/_protected'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/_protected/dashboard/': {
      id: '/app/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppProtectedDashboardIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/withdrawals/': {
      id: '/app/_protected/payment-internal/withdrawals/'
      path: '/payment-internal/withdrawals'
      fullPath: '/app/payment-internal/withdrawals/'
      preLoaderRoute: typeof AppProtectedPaymentInternalWithdrawalsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/transactions/': {
      id: '/app/_protected/payment-internal/transactions/'
      path: '/payment-internal/transactions'
      fullPath: '/app/payment-internal/transactions/'
      preLoaderRoute: typeof AppProtectedPaymentInternalTransactionsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/subscriptions/': {
      id: '/app/_protected/payment-internal/subscriptions/'
      path: '/payment-internal/subscriptions'
      fullPath: '/app/payment-internal/subscriptions/'
      preLoaderRoute: typeof AppProtectedPaymentInternalSubscriptionsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/services/': {
      id: '/app/_protected/payment-internal/services/'
      path: '/payment-internal/services'
      fullPath: '/app/payment-internal/services/'
      preLoaderRoute: typeof AppProtectedPaymentInternalServicesIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/notifications/': {
      id: '/app/_protected/payment-internal/notifications/'
      path: '/payment-internal/notifications'
      fullPath: '/app/payment-internal/notifications/'
      preLoaderRoute: typeof AppProtectedPaymentInternalNotificationsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/merchants/': {
      id: '/app/_protected/payment-internal/merchants/'
      path: '/payment-internal/merchants'
      fullPath: '/app/payment-internal/merchants/'
      preLoaderRoute: typeof AppProtectedPaymentInternalMerchantsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/invoices/': {
      id: '/app/_protected/payment-internal/invoices/'
      path: '/payment-internal/invoices'
      fullPath: '/app/payment-internal/invoices/'
      preLoaderRoute: typeof AppProtectedPaymentInternalInvoicesIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/incidents/': {
      id: '/app/_protected/payment-internal/incidents/'
      path: '/payment-internal/incidents'
      fullPath: '/app/payment-internal/incidents/'
      preLoaderRoute: typeof AppProtectedPaymentInternalIncidentsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/channels/': {
      id: '/app/_protected/payment-internal/channels/'
      path: '/payment-internal/channels'
      fullPath: '/app/payment-internal/channels/'
      preLoaderRoute: typeof AppProtectedPaymentInternalChannelsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/withdrawals/': {
      id: '/app/_protected/payment-admin/withdrawals/'
      path: '/payment-admin/withdrawals'
      fullPath: '/app/payment-admin/withdrawals/'
      preLoaderRoute: typeof AppProtectedPaymentAdminWithdrawalsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/transactions/': {
      id: '/app/_protected/payment-admin/transactions/'
      path: '/payment-admin/transactions'
      fullPath: '/app/payment-admin/transactions/'
      preLoaderRoute: typeof AppProtectedPaymentAdminTransactionsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/services/': {
      id: '/app/_protected/payment-admin/services/'
      path: '/payment-admin/services'
      fullPath: '/app/payment-admin/services/'
      preLoaderRoute: typeof AppProtectedPaymentAdminServicesIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/service-status/': {
      id: '/app/_protected/payment-admin/service-status/'
      path: '/payment-admin/service-status'
      fullPath: '/app/payment-admin/service-status/'
      preLoaderRoute: typeof AppProtectedPaymentAdminServiceStatusIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/mutations/': {
      id: '/app/_protected/payment-admin/mutations/'
      path: '/payment-admin/mutations'
      fullPath: '/app/payment-admin/mutations/'
      preLoaderRoute: typeof AppProtectedPaymentAdminMutationsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/subscriptions/$subscriptionId/': {
      id: '/app/_protected/payment-internal/subscriptions/$subscriptionId/'
      path: '/payment-internal/subscriptions/$subscriptionId'
      fullPath: '/app/payment-internal/subscriptions/$subscriptionId/'
      preLoaderRoute: typeof AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/invoices/$invoiceId/': {
      id: '/app/_protected/payment-internal/invoices/$invoiceId/'
      path: '/payment-internal/invoices/$invoiceId'
      fullPath: '/app/payment-internal/invoices/$invoiceId/'
      preLoaderRoute: typeof AppProtectedPaymentInternalInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/service-invoices/$invoiceId/': {
      id: '/app/_protected/payment-admin/service-invoices/$invoiceId/'
      path: '/payment-admin/service-invoices/$invoiceId'
      fullPath: '/app/payment-admin/service-invoices/$invoiceId/'
      preLoaderRoute: typeof AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/services/$serviceId/checkout/': {
      id: '/app/_protected/payment-admin/services/$serviceId/checkout/'
      path: '/payment-admin/services/$serviceId/checkout'
      fullPath: '/app/payment-admin/services/$serviceId/checkout/'
      preLoaderRoute: typeof AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppProtectedRouteChildren {
  AppProtectedDashboardIndexRoute: typeof AppProtectedDashboardIndexRoute
  AppProtectedPaymentAdminMutationsIndexRoute: typeof AppProtectedPaymentAdminMutationsIndexRoute
  AppProtectedPaymentAdminServiceStatusIndexRoute: typeof AppProtectedPaymentAdminServiceStatusIndexRoute
  AppProtectedPaymentAdminServicesIndexRoute: typeof AppProtectedPaymentAdminServicesIndexRoute
  AppProtectedPaymentAdminTransactionsIndexRoute: typeof AppProtectedPaymentAdminTransactionsIndexRoute
  AppProtectedPaymentAdminWithdrawalsIndexRoute: typeof AppProtectedPaymentAdminWithdrawalsIndexRoute
  AppProtectedPaymentInternalChannelsIndexRoute: typeof AppProtectedPaymentInternalChannelsIndexRoute
  AppProtectedPaymentInternalIncidentsIndexRoute: typeof AppProtectedPaymentInternalIncidentsIndexRoute
  AppProtectedPaymentInternalInvoicesIndexRoute: typeof AppProtectedPaymentInternalInvoicesIndexRoute
  AppProtectedPaymentInternalMerchantsIndexRoute: typeof AppProtectedPaymentInternalMerchantsIndexRoute
  AppProtectedPaymentInternalNotificationsIndexRoute: typeof AppProtectedPaymentInternalNotificationsIndexRoute
  AppProtectedPaymentInternalServicesIndexRoute: typeof AppProtectedPaymentInternalServicesIndexRoute
  AppProtectedPaymentInternalSubscriptionsIndexRoute: typeof AppProtectedPaymentInternalSubscriptionsIndexRoute
  AppProtectedPaymentInternalTransactionsIndexRoute: typeof AppProtectedPaymentInternalTransactionsIndexRoute
  AppProtectedPaymentInternalWithdrawalsIndexRoute: typeof AppProtectedPaymentInternalWithdrawalsIndexRoute
  AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRoute: typeof AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRoute
  AppProtectedPaymentInternalInvoicesInvoiceIdIndexRoute: typeof AppProtectedPaymentInternalInvoicesInvoiceIdIndexRoute
  AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRoute: typeof AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRoute
  AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRoute: typeof AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRoute
}

const AppProtectedRouteChildren: AppProtectedRouteChildren = {
  AppProtectedDashboardIndexRoute: AppProtectedDashboardIndexRoute,
  AppProtectedPaymentAdminMutationsIndexRoute:
    AppProtectedPaymentAdminMutationsIndexRoute,
  AppProtectedPaymentAdminServiceStatusIndexRoute:
    AppProtectedPaymentAdminServiceStatusIndexRoute,
  AppProtectedPaymentAdminServicesIndexRoute:
    AppProtectedPaymentAdminServicesIndexRoute,
  AppProtectedPaymentAdminTransactionsIndexRoute:
    AppProtectedPaymentAdminTransactionsIndexRoute,
  AppProtectedPaymentAdminWithdrawalsIndexRoute:
    AppProtectedPaymentAdminWithdrawalsIndexRoute,
  AppProtectedPaymentInternalChannelsIndexRoute:
    AppProtectedPaymentInternalChannelsIndexRoute,
  AppProtectedPaymentInternalIncidentsIndexRoute:
    AppProtectedPaymentInternalIncidentsIndexRoute,
  AppProtectedPaymentInternalInvoicesIndexRoute:
    AppProtectedPaymentInternalInvoicesIndexRoute,
  AppProtectedPaymentInternalMerchantsIndexRoute:
    AppProtectedPaymentInternalMerchantsIndexRoute,
  AppProtectedPaymentInternalNotificationsIndexRoute:
    AppProtectedPaymentInternalNotificationsIndexRoute,
  AppProtectedPaymentInternalServicesIndexRoute:
    AppProtectedPaymentInternalServicesIndexRoute,
  AppProtectedPaymentInternalSubscriptionsIndexRoute:
    AppProtectedPaymentInternalSubscriptionsIndexRoute,
  AppProtectedPaymentInternalTransactionsIndexRoute:
    AppProtectedPaymentInternalTransactionsIndexRoute,
  AppProtectedPaymentInternalWithdrawalsIndexRoute:
    AppProtectedPaymentInternalWithdrawalsIndexRoute,
  AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRoute:
    AppProtectedPaymentAdminServiceInvoicesInvoiceIdIndexRoute,
  AppProtectedPaymentInternalInvoicesInvoiceIdIndexRoute:
    AppProtectedPaymentInternalInvoicesInvoiceIdIndexRoute,
  AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRoute:
    AppProtectedPaymentInternalSubscriptionsSubscriptionIdIndexRoute,
  AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRoute:
    AppProtectedPaymentAdminServicesServiceIdCheckoutIndexRoute,
}

const AppProtectedRouteWithChildren = AppProtectedRoute._addFileChildren(
  AppProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppProtectedRoute: AppProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
