/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProtectedRouteImport } from './routes/app/_protected'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AppProtectedDashboardIndexRouteImport } from './routes/app/_protected/dashboard/index'
import { Route as AppProtectedPaymentInternalWithdrawalsIndexRouteImport } from './routes/app/_protected/payment-internal/withdrawals/index'
import { Route as AppProtectedPaymentInternalTransactionsIndexRouteImport } from './routes/app/_protected/payment-internal/transactions/index'
import { Route as AppProtectedPaymentInternalMerchantsIndexRouteImport } from './routes/app/_protected/payment-internal/merchants/index'
import { Route as AppProtectedPaymentInternalChannelsIndexRouteImport } from './routes/app/_protected/payment-internal/channels/index'
import { Route as AppProtectedPaymentInternalAdminFeeIndexRouteImport } from './routes/app/_protected/payment-internal/admin-fee/index'
import { Route as AppProtectedPaymentAdminWithdrawalsIndexRouteImport } from './routes/app/_protected/payment-admin/withdrawals/index'
import { Route as AppProtectedPaymentAdminTransactionsIndexRouteImport } from './routes/app/_protected/payment-admin/transactions/index'
import { Route as AppProtectedPaymentAdminMutationsIndexRouteImport } from './routes/app/_protected/payment-admin/mutations/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/app/_protected',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppProtectedDashboardIndexRoute =
  AppProtectedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalWithdrawalsIndexRoute =
  AppProtectedPaymentInternalWithdrawalsIndexRouteImport.update({
    id: '/payment-internal/withdrawals/',
    path: '/payment-internal/withdrawals/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalTransactionsIndexRoute =
  AppProtectedPaymentInternalTransactionsIndexRouteImport.update({
    id: '/payment-internal/transactions/',
    path: '/payment-internal/transactions/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalMerchantsIndexRoute =
  AppProtectedPaymentInternalMerchantsIndexRouteImport.update({
    id: '/payment-internal/merchants/',
    path: '/payment-internal/merchants/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalChannelsIndexRoute =
  AppProtectedPaymentInternalChannelsIndexRouteImport.update({
    id: '/payment-internal/channels/',
    path: '/payment-internal/channels/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentInternalAdminFeeIndexRoute =
  AppProtectedPaymentInternalAdminFeeIndexRouteImport.update({
    id: '/payment-internal/admin-fee/',
    path: '/payment-internal/admin-fee/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminWithdrawalsIndexRoute =
  AppProtectedPaymentAdminWithdrawalsIndexRouteImport.update({
    id: '/payment-admin/withdrawals/',
    path: '/payment-admin/withdrawals/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminTransactionsIndexRoute =
  AppProtectedPaymentAdminTransactionsIndexRouteImport.update({
    id: '/payment-admin/transactions/',
    path: '/payment-admin/transactions/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedPaymentAdminMutationsIndexRoute =
  AppProtectedPaymentAdminMutationsIndexRouteImport.update({
    id: '/payment-admin/mutations/',
    path: '/payment-admin/mutations/',
    getParentRoute: () => AppProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppProtectedRouteWithChildren
  '/login/': typeof AuthLoginIndexRoute
  '/app/dashboard/': typeof AppProtectedDashboardIndexRoute
  '/app/payment-admin/mutations/': typeof AppProtectedPaymentAdminMutationsIndexRoute
  '/app/payment-admin/transactions/': typeof AppProtectedPaymentAdminTransactionsIndexRoute
  '/app/payment-admin/withdrawals/': typeof AppProtectedPaymentAdminWithdrawalsIndexRoute
  '/app/payment-internal/admin-fee/': typeof AppProtectedPaymentInternalAdminFeeIndexRoute
  '/app/payment-internal/channels/': typeof AppProtectedPaymentInternalChannelsIndexRoute
  '/app/payment-internal/merchants/': typeof AppProtectedPaymentInternalMerchantsIndexRoute
  '/app/payment-internal/transactions/': typeof AppProtectedPaymentInternalTransactionsIndexRoute
  '/app/payment-internal/withdrawals/': typeof AppProtectedPaymentInternalWithdrawalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppProtectedRouteWithChildren
  '/login': typeof AuthLoginIndexRoute
  '/app/dashboard': typeof AppProtectedDashboardIndexRoute
  '/app/payment-admin/mutations': typeof AppProtectedPaymentAdminMutationsIndexRoute
  '/app/payment-admin/transactions': typeof AppProtectedPaymentAdminTransactionsIndexRoute
  '/app/payment-admin/withdrawals': typeof AppProtectedPaymentAdminWithdrawalsIndexRoute
  '/app/payment-internal/admin-fee': typeof AppProtectedPaymentInternalAdminFeeIndexRoute
  '/app/payment-internal/channels': typeof AppProtectedPaymentInternalChannelsIndexRoute
  '/app/payment-internal/merchants': typeof AppProtectedPaymentInternalMerchantsIndexRoute
  '/app/payment-internal/transactions': typeof AppProtectedPaymentInternalTransactionsIndexRoute
  '/app/payment-internal/withdrawals': typeof AppProtectedPaymentInternalWithdrawalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app/_protected': typeof AppProtectedRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/app/_protected/dashboard/': typeof AppProtectedDashboardIndexRoute
  '/app/_protected/payment-admin/mutations/': typeof AppProtectedPaymentAdminMutationsIndexRoute
  '/app/_protected/payment-admin/transactions/': typeof AppProtectedPaymentAdminTransactionsIndexRoute
  '/app/_protected/payment-admin/withdrawals/': typeof AppProtectedPaymentAdminWithdrawalsIndexRoute
  '/app/_protected/payment-internal/admin-fee/': typeof AppProtectedPaymentInternalAdminFeeIndexRoute
  '/app/_protected/payment-internal/channels/': typeof AppProtectedPaymentInternalChannelsIndexRoute
  '/app/_protected/payment-internal/merchants/': typeof AppProtectedPaymentInternalMerchantsIndexRoute
  '/app/_protected/payment-internal/transactions/': typeof AppProtectedPaymentInternalTransactionsIndexRoute
  '/app/_protected/payment-internal/withdrawals/': typeof AppProtectedPaymentInternalWithdrawalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login/'
    | '/app/dashboard/'
    | '/app/payment-admin/mutations/'
    | '/app/payment-admin/transactions/'
    | '/app/payment-admin/withdrawals/'
    | '/app/payment-internal/admin-fee/'
    | '/app/payment-internal/channels/'
    | '/app/payment-internal/merchants/'
    | '/app/payment-internal/transactions/'
    | '/app/payment-internal/withdrawals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/payment-admin/mutations'
    | '/app/payment-admin/transactions'
    | '/app/payment-admin/withdrawals'
    | '/app/payment-internal/admin-fee'
    | '/app/payment-internal/channels'
    | '/app/payment-internal/merchants'
    | '/app/payment-internal/transactions'
    | '/app/payment-internal/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app/_protected'
    | '/_auth/login/'
    | '/app/_protected/dashboard/'
    | '/app/_protected/payment-admin/mutations/'
    | '/app/_protected/payment-admin/transactions/'
    | '/app/_protected/payment-admin/withdrawals/'
    | '/app/_protected/payment-internal/admin-fee/'
    | '/app/_protected/payment-internal/channels/'
    | '/app/_protected/payment-internal/merchants/'
    | '/app/_protected/payment-internal/transactions/'
    | '/app/_protected/payment-internal/withdrawals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppProtectedRoute: typeof AppProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_protected': {
      id: '/app/_protected'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/_protected/dashboard/': {
      id: '/app/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppProtectedDashboardIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/withdrawals/': {
      id: '/app/_protected/payment-internal/withdrawals/'
      path: '/payment-internal/withdrawals'
      fullPath: '/app/payment-internal/withdrawals/'
      preLoaderRoute: typeof AppProtectedPaymentInternalWithdrawalsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/transactions/': {
      id: '/app/_protected/payment-internal/transactions/'
      path: '/payment-internal/transactions'
      fullPath: '/app/payment-internal/transactions/'
      preLoaderRoute: typeof AppProtectedPaymentInternalTransactionsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/merchants/': {
      id: '/app/_protected/payment-internal/merchants/'
      path: '/payment-internal/merchants'
      fullPath: '/app/payment-internal/merchants/'
      preLoaderRoute: typeof AppProtectedPaymentInternalMerchantsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/channels/': {
      id: '/app/_protected/payment-internal/channels/'
      path: '/payment-internal/channels'
      fullPath: '/app/payment-internal/channels/'
      preLoaderRoute: typeof AppProtectedPaymentInternalChannelsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-internal/admin-fee/': {
      id: '/app/_protected/payment-internal/admin-fee/'
      path: '/payment-internal/admin-fee'
      fullPath: '/app/payment-internal/admin-fee/'
      preLoaderRoute: typeof AppProtectedPaymentInternalAdminFeeIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/withdrawals/': {
      id: '/app/_protected/payment-admin/withdrawals/'
      path: '/payment-admin/withdrawals'
      fullPath: '/app/payment-admin/withdrawals/'
      preLoaderRoute: typeof AppProtectedPaymentAdminWithdrawalsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/transactions/': {
      id: '/app/_protected/payment-admin/transactions/'
      path: '/payment-admin/transactions'
      fullPath: '/app/payment-admin/transactions/'
      preLoaderRoute: typeof AppProtectedPaymentAdminTransactionsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/app/_protected/payment-admin/mutations/': {
      id: '/app/_protected/payment-admin/mutations/'
      path: '/payment-admin/mutations'
      fullPath: '/app/payment-admin/mutations/'
      preLoaderRoute: typeof AppProtectedPaymentAdminMutationsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppProtectedRouteChildren {
  AppProtectedDashboardIndexRoute: typeof AppProtectedDashboardIndexRoute
  AppProtectedPaymentAdminMutationsIndexRoute: typeof AppProtectedPaymentAdminMutationsIndexRoute
  AppProtectedPaymentAdminTransactionsIndexRoute: typeof AppProtectedPaymentAdminTransactionsIndexRoute
  AppProtectedPaymentAdminWithdrawalsIndexRoute: typeof AppProtectedPaymentAdminWithdrawalsIndexRoute
  AppProtectedPaymentInternalAdminFeeIndexRoute: typeof AppProtectedPaymentInternalAdminFeeIndexRoute
  AppProtectedPaymentInternalChannelsIndexRoute: typeof AppProtectedPaymentInternalChannelsIndexRoute
  AppProtectedPaymentInternalMerchantsIndexRoute: typeof AppProtectedPaymentInternalMerchantsIndexRoute
  AppProtectedPaymentInternalTransactionsIndexRoute: typeof AppProtectedPaymentInternalTransactionsIndexRoute
  AppProtectedPaymentInternalWithdrawalsIndexRoute: typeof AppProtectedPaymentInternalWithdrawalsIndexRoute
}

const AppProtectedRouteChildren: AppProtectedRouteChildren = {
  AppProtectedDashboardIndexRoute: AppProtectedDashboardIndexRoute,
  AppProtectedPaymentAdminMutationsIndexRoute:
    AppProtectedPaymentAdminMutationsIndexRoute,
  AppProtectedPaymentAdminTransactionsIndexRoute:
    AppProtectedPaymentAdminTransactionsIndexRoute,
  AppProtectedPaymentAdminWithdrawalsIndexRoute:
    AppProtectedPaymentAdminWithdrawalsIndexRoute,
  AppProtectedPaymentInternalAdminFeeIndexRoute:
    AppProtectedPaymentInternalAdminFeeIndexRoute,
  AppProtectedPaymentInternalChannelsIndexRoute:
    AppProtectedPaymentInternalChannelsIndexRoute,
  AppProtectedPaymentInternalMerchantsIndexRoute:
    AppProtectedPaymentInternalMerchantsIndexRoute,
  AppProtectedPaymentInternalTransactionsIndexRoute:
    AppProtectedPaymentInternalTransactionsIndexRoute,
  AppProtectedPaymentInternalWithdrawalsIndexRoute:
    AppProtectedPaymentInternalWithdrawalsIndexRoute,
}

const AppProtectedRouteWithChildren = AppProtectedRoute._addFileChildren(
  AppProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppProtectedRoute: AppProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
