/**
 * Bank / e-wallet options for the withdrawal (disbursement) form.
 *
 * `code` is sent to the API as `bank_code` and forwarded to Monetapay as
 * `account_bank_code`. Mirror of the backend `config/banks.php` — keep the two
 * in sync. Codes in `EWALLET_CODES` are paid out via Monetapay's e-wallet payout
 * (keyed on the phone, no account number); everything else is a bank transfer.
 */
export const EWALLET_CODES = ["OVO", "DANA", "LINKAJA", "SHOPEEPAY", "GOPAY"] as const;

type BankEntry = { code: string; name: string };

const BANKS: BankEntry[] = [
  { code: "ANGLOMAS", name: "Anglomas International Bank" },
  { code: "BANGKOK", name: "Bangkok Bank" },
  { code: "AGRIS", name: "Bank Agris" },
  { code: "AGRONIAGA", name: "Bank Agroniaga" },
  { code: "AMAR", name: "Bank Amar Indonesia" },
  { code: "ANDARA", name: "Bank Andara" },
  { code: "ANZ", name: "Bank ANZ Indonesia" },
  { code: "ARTA_NIAGA_KENCANA", name: "Bank Arta Niaga Kencana" },
  { code: "ARTHA", name: "Bank Artha Graha International" },
  { code: "ARTOS", name: "Bank Artos Indonesia" },
  { code: "BISNIS_INTERNASIONAL", name: "Bank Bisnis Internasional" },
  { code: "BJB", name: "Bank BJB" },
  { code: "BJB_SYR", name: "Bank BJB Syariah" },
  { code: "BNI_SYR", name: "Bank BNI Syariah" },
  { code: "BNP_PARIBAS", name: "Bank BNP Paribas" },
  { code: "BUKOPIN", name: "Bank Bukopin" },
  { code: "BUMI_ARTA", name: "Bank Bumi Arta" },
  { code: "CAPITAL", name: "Bank Capital Indonesia" },
  { code: "BCA", name: "Bank Central Asia (BCA)" },
  { code: "BCA_SYR", name: "Bank Central Asia (BCA) Syariah" },
  { code: "CHINATRUST", name: "Bank Chinatrust Indonesia" },
  { code: "CIMB", name: "Bank CIMB Niaga" },
  { code: "CIMB_UUS", name: "Bank CIMB Niaga UUS" },
  { code: "COMMONWEALTH", name: "Bank Commonwealth" },
  { code: "DANAMON", name: "Bank Danamon" },
  { code: "DANAMON_UUS", name: "Bank Danamon UUS" },
  { code: "DBS", name: "Bank DBS Indonesia" },
  { code: "DINAR_INDONESIA", name: "Bank Dinar Indonesia" },
  { code: "DKI", name: "Bank DKI" },
  { code: "DKI_UUS", name: "Bank DKI UUS" },
  { code: "FAMA", name: "Bank Fama International" },
  { code: "GANESHA", name: "Bank Ganesha" },
  { code: "HANA", name: "Bank Hana" },
  { code: "HARDA_INTERNASIONAL", name: "Bank Harda Internasional" },
  { code: "HIMPUNAN_SAUDARA", name: "Bank Himpunan Saudara 1906" },
  { code: "ICBC", name: "Bank ICBC Indonesia" },
  { code: "INA_PERDANA", name: "Bank Ina Perdania" },
  { code: "INDEX_SELINDO", name: "Bank Index Selindo" },
  { code: "JASA_JAKARTA", name: "Bank Jasa Jakarta" },
  { code: "JTRUST", name: "Bank JTrust Indonesia" },
  { code: "KESEJAHTERAAN_EKONOMI", name: "Bank Kesejahteraan Ekonomi" },
  { code: "MANDIRI", name: "Bank Mandiri" },
  { code: "MASPION", name: "Bank Maspion Indonesia" },
  { code: "MAYAPADA", name: "Bank Mayapada International" },
  { code: "MAYBANK", name: "Bank Maybank" },
  { code: "MAYBANK_SYR", name: "Bank Maybank Syariah Indonesia" },
  { code: "MAYORA", name: "Bank Mayora" },
  { code: "MEGA", name: "Bank Mega" },
  { code: "MESTIKA_DHARMA", name: "Bank Mestika Dharma" },
  { code: "MITRA_NIAGA", name: "Bank Mitra Niaga" },
  { code: "MIZUHO", name: "Bank Mizuho Indonesia" },
  { code: "MNC_INTERNASIONAL", name: "Bank MNC Internasional" },
  { code: "MUAMALAT", name: "Bank Muamalat Indonesia" },
  { code: "MULTI_ARTA_SENTOSA", name: "Bank Multi Arta Sentosa" },
  { code: "NATIONALNOBU", name: "Bank Nationalnobu" },
  { code: "BNI", name: "Bank Negara Indonesia (BNI)" },
  { code: "NUSANTARA_PARAHYANGAN", name: "Bank Nusantara Parahyangan" },
  { code: "OCBC", name: "Bank OCBC NISP" },
  { code: "OCBC_UUS", name: "Bank OCBC NISP UUS" },
  { code: "BAML", name: "Bank of America Merill-Lynch" },
  { code: "BOC", name: "Bank of China (BOC)" },
  { code: "INDIA", name: "Bank of India Indonesia" },
  { code: "TOKYO", name: "Bank of Tokyo Mitsubishi UFJ" },
  { code: "OKE", name: "Bank Oke Indonesia" },
  { code: "PANIN", name: "Bank Panin" },
  { code: "PANIN_SYR", name: "Bank Panin Syariah" },
  { code: "PERMATA", name: "Bank Permata" },
  { code: "PERMATA_UUS", name: "Bank Permata UUS" },
  { code: "QNB_INDONESIA", name: "Bank QNB Indonesia" },
  { code: "RABOBANK", name: "Bank Rabobank International Indonesia" },
  { code: "BRI", name: "Bank Rakyat Indonesia (BRI)" },
  { code: "RESONA", name: "Bank Resona Perdania" },
  { code: "ROYAL", name: "Bank Royal Indonesia" },
  { code: "SAHABAT_SAMPOERNA", name: "Bank Sahabat Sampoerna" },
  { code: "SBI_INDONESIA", name: "Bank SBI Indonesia" },
  { code: "SHINHAN", name: "Bank Shinhan Indonesia" },
  { code: "SINARMAS", name: "Bank Sinarmas" },
  { code: "SINARMAS_UUS", name: "Bank Sinarmas UUS" },
  { code: "MITSUI", name: "Bank Sumitomo Mitsui Indonesia" },
  { code: "BRI_SYR", name: "Bank Syariah BRI" },
  { code: "BUKOPIN_SYR", name: "Bank Syariah Bukopin" },
  { code: "MANDIRI_SYR", name: "Bank Syariah Mandiri" },
  { code: "MEGA_SYR", name: "Bank Syariah Mega" },
  { code: "BTN", name: "Bank Tabungan Negara (BTN)" },
  { code: "BTN_UUS", name: "Bank Tabungan Negara (BTN) UUS" },
  { code: "TABUNGAN_PENSIUNAN_NASIONAL", name: "Bank Tabungan Pensiunan Nasional" },
  { code: "BTPN", name: "Bank Tabungan Pensiunan Nasional (BTPN)" },
  { code: "UOB", name: "Bank UOB Indonesia" },
  { code: "VICTORIA_INTERNASIONAL", name: "Bank Victoria Internasional" },
  { code: "VICTORIA_SYR", name: "Bank Victoria Syariah" },
  { code: "WOORI", name: "Bank Woori Indonesia" },
  { code: "WOORI_SAUDARA", name: "Bank Woori Saudara Indonesia 1906" },
  { code: "YUDHA_BHAKTI", name: "Bank Yudha Bhakti" },
  { code: "ACEH", name: "BPD Aceh" },
  { code: "ACEH_UUS", name: "BPD Aceh UUS" },
  { code: "BANTEN", name: "BPD Banten" },
  { code: "BENGKULU", name: "BPD Bengkulu" },
  { code: "DAERAH_ISTIMEWA_UUS", name: "BPD Daerah Istimewa Yogyakarta (DIY) UUS" },
  { code: "JAMBI", name: "BPD Jambi" },
  { code: "JAMBI_UUS", name: "BPD Jambi UUS" },
  { code: "JAWA_TENGAH", name: "BPD Jawa Tengah" },
  { code: "JAWA_TENGAH_UUS", name: "BPD Jawa Tengah UUS" },
  { code: "JAWA_TIMUR", name: "BPD Jawa Timur" },
  { code: "JAWA_TIMUR_UUS", name: "BPD Jawa Timur UUS" },
  { code: "KALIMANTAN_BARAT", name: "BPD Kalimantan Barat" },
  { code: "KALIMANTAN_BARAT_UUS", name: "BPD Kalimantan Barat UUS" },
  { code: "KALIMANTAN_SELATAN", name: "BPD Kalimantan Selatan" },
  { code: "KALIMANTAN_SELATAN_UUS", name: "BPD Kalimantan Selatan UUS" },
  { code: "KALIMANTAN_TENGAH", name: "BPD Kalimantan Tengah" },
  { code: "KALIMANTAN_TIMUR", name: "BPD Kalimantan Timur" },
  { code: "KALIMANTAN_TIMUR_UUS", name: "BPD Kalimantan Timur UUS" },
  { code: "LAMPUNG", name: "BPD Lampung" },
  { code: "MALUKU", name: "BPD Maluku" },
  { code: "NUSA_TENGGARA_BARAT", name: "BPD Nusa Tenggara Barat" },
  { code: "NUSA_TENGGARA_BARAT_UUS", name: "BPD Nusa Tenggara Barat UUS" },
  { code: "NUSA_TENGGARA_TIMUR", name: "BPD Nusa Tenggara Timur" },
  { code: "PAPUA", name: "BPD Papua" },
  { code: "RIAU_DAN_KEPRI", name: "BPD Riau Dan Kepri" },
  { code: "RIAU_DAN_KEPRI_UUS", name: "BPD Riau Dan Kepri UUS" },
  { code: "SULAWESI", name: "BPD Sulawesi Tengah" },
  { code: "SULAWESI_TENGGARA", name: "BPD Sulawesi Tenggara" },
  { code: "SULSELBAR", name: "BPD Sulselbar" },
  { code: "SULSELBAR_UUS", name: "BPD Sulselbar UUS" },
  { code: "SULUT", name: "BPD Sulut" },
  { code: "SUMATERA_BARAT", name: "BPD Sumatera Barat" },
  { code: "SUMATERA_BARAT_UUS", name: "BPD Sumatera Barat UUS" },
  { code: "SUMSEL_DAN_BABEL", name: "BPD Sumsel Dan Babel" },
  { code: "SUMSEL_DAN_BABEL_UUS", name: "BPD Sumsel Dan Babel UUS" },
  { code: "SUMUT", name: "BPD Sumut" },
  { code: "SUMUT_UUS", name: "BPD Sumut UUS" },
  { code: "BTPN_SYARIAH", name: "BTPN Syariah" },
  { code: "CENTRATAMA", name: "Centratama Nasional Bank" },
  { code: "CCB", name: "China Construction Bank Indonesia" },
  { code: "CITIBANK", name: "Citibank" },
  { code: "DEUTSCHE", name: "Deutsche Bank" },
  { code: "HSBC_UUS", name: "HSBC UUS" },
  { code: "HSBC", name: "HSBC Indonesia" },
  { code: "EXIMBANK", name: "Indonesia Eximbank" },
  { code: "JPMORGAN", name: "JP Morgan Chase Bank" },
  { code: "MANDIRI_TASPEN", name: "Mandiri Taspen Pos" },
  { code: "PRIMA_MASTER", name: "Prima Master Bank" },
  { code: "RBS", name: "Royal Bank of Scotland (RBS)" },
  { code: "STANDARD_CHARTERED", name: "Standard Chartered Bank" },
  { code: "BSI", name: "Bank Syariah Indonesia (BSI)" },
  { code: "BNC", name: "Bank Neo Commerce" },
  { code: "SEABANK", name: "Bank Seabank Indonesia" },
  { code: "BSS", name: "Bank Sahabat Sampoerna (BSS)" },
  { code: "ALLO", name: "Allo Bank Indonesia" },
  { code: "JAGO", name: "Bank Jago" },
  { code: "IBK", name: "Bank IBK Indonesia" },
  { code: "ALADIN", name: "Bank Aladin Syariah" },
  { code: "BALI", name: "BPD Bali" },
  { code: "BCA_DIGITAL", name: "Bank Digital BCA" },
  { code: "JAGO_UUS", name: "Bank Jago UUS" },
  { code: "CTBC", name: "Bank CTBC Indonesia" },
  { code: "NAGARI", name: "Bank Nagari" },
  { code: "NAGARI_UUS", name: "Bank Nagari UUS" },
  { code: "DIY_UUS", name: "BPD DIY UUS" },
  { code: "JABAR_BANTEN_SYR", name: "Bank Jabar Banten Syariah" },
  { code: "AGI", name: "Bank Artha Graha Internasional" },
  { code: "RAYA", name: "Bank Raya Indonesia" },
  { code: "BI", name: "Bank Indonesia" },
  { code: "KSEI", name: "PT. KSEI" },
  { code: "NTT", name: "BPD NTT" },
  { code: "DAERAH_ISTIMEWA", name: "BPD Daerah Istimewa Yogyakarta (DIY)" },
  // E-wallets
  { code: "OVO", name: "OVO" },
  { code: "DANA", name: "DANA" },
  { code: "LINKAJA", name: "LinkAja" },
  { code: "SHOPEEPAY", name: "ShopeePay" },
  { code: "GOPAY", name: "GoPay" },
];

export const BANK_OPTIONS = BANKS.map((b) => ({
  code: b.code,
  label: `${b.code} — ${b.name}`,
})) as ReadonlyArray<{ code: string; label: string }>;

/** Bank codes as a tuple, for schema validation. */
export const BANK_CODES = BANK_OPTIONS.map((b) => b.code) as [string, ...string[]];

/** True when the code is paid out via Monetapay e-wallet payout (phone, no account no.). */
export function isEwalletCode(code: string | undefined | null): boolean {
  return !!code && (EWALLET_CODES as readonly string[]).includes(code);
}
