/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAuthRouteRouteImport } from './routes/$locale/_auth/route'
import { Route as LocaleLeaderboardIndexRouteImport } from './routes/$locale/leaderboard/index'
import { Route as LocaleKebijakanPrivasiIndexRouteImport } from './routes/$locale/kebijakan-privasi/index'
import { Route as LocaleKalkulatorZodiacIndexRouteImport } from './routes/$locale/kalkulator-zodiac/index'
import { Route as LocaleKalkulatorWinRateIndexRouteImport } from './routes/$locale/kalkulator-win-rate/index'
import { Route as LocaleKalkulatorMagicWheelIndexRouteImport } from './routes/$locale/kalkulator-magic-wheel/index'
import { Route as LocaleFaqIndexRouteImport } from './routes/$locale/faq/index'
import { Route as LocaleDaftarHargaIndexRouteImport } from './routes/$locale/daftar-harga/index'
import { Route as LocaleCekPesananIndexRouteImport } from './routes/$locale/cek-pesanan/index'
import { Route as LocaleBeritaIndexRouteImport } from './routes/$locale/berita/index'
import { Route as LocaleCheckoutGameSlugRouteImport } from './routes/$locale/checkout/$gameSlug'
import { Route as LocaleBeritaSlugRouteImport } from './routes/$locale/berita/$slug'
import { Route as LocaleInvoiceInvoiceNumberIndexRouteImport } from './routes/$locale/invoice/$invoiceNumber/index'
import { Route as LocaleAuthRegisterIndexRouteImport } from './routes/$locale/_auth/register/index'
import { Route as LocaleAuthLoginIndexRouteImport } from './routes/$locale/_auth/login/index'
import { Route as LocaleAuthForgotPasswordIndexRouteImport } from './routes/$locale/_auth/forgot-password/index'
import { Route as LocaleInvoiceInvoiceNumberSuccessRouteImport } from './routes/$locale/invoice/$invoiceNumber/success'
import { Route as LocaleInvoiceInvoiceNumberFailedRouteImport } from './routes/$locale/invoice/$invoiceNumber/failed'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAuthRouteRoute = LocaleAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLeaderboardIndexRoute = LocaleLeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleKebijakanPrivasiIndexRoute =
  LocaleKebijakanPrivasiIndexRouteImport.update({
    id: '/kebijakan-privasi/',
    path: '/kebijakan-privasi/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleKalkulatorZodiacIndexRoute =
  LocaleKalkulatorZodiacIndexRouteImport.update({
    id: '/kalkulator-zodiac/',
    path: '/kalkulator-zodiac/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleKalkulatorWinRateIndexRoute =
  LocaleKalkulatorWinRateIndexRouteImport.update({
    id: '/kalkulator-win-rate/',
    path: '/kalkulator-win-rate/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleKalkulatorMagicWheelIndexRoute =
  LocaleKalkulatorMagicWheelIndexRouteImport.update({
    id: '/kalkulator-magic-wheel/',
    path: '/kalkulator-magic-wheel/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleFaqIndexRoute = LocaleFaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDaftarHargaIndexRoute = LocaleDaftarHargaIndexRouteImport.update({
  id: '/daftar-harga/',
  path: '/daftar-harga/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCekPesananIndexRoute = LocaleCekPesananIndexRouteImport.update({
  id: '/cek-pesanan/',
  path: '/cek-pesanan/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBeritaIndexRoute = LocaleBeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCheckoutGameSlugRoute = LocaleCheckoutGameSlugRouteImport.update({
  id: '/checkout/$gameSlug',
  path: '/checkout/$gameSlug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBeritaSlugRoute = LocaleBeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleInvoiceInvoiceNumberIndexRoute =
  LocaleInvoiceInvoiceNumberIndexRouteImport.update({
    id: '/invoice/$invoiceNumber/',
    path: '/invoice/$invoiceNumber/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleAuthRegisterIndexRoute = LocaleAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => LocaleAuthRouteRoute,
} as any)
const LocaleAuthLoginIndexRoute = LocaleAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LocaleAuthRouteRoute,
} as any)
const LocaleAuthForgotPasswordIndexRoute =
  LocaleAuthForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => LocaleAuthRouteRoute,
  } as any)
const LocaleInvoiceInvoiceNumberSuccessRoute =
  LocaleInvoiceInvoiceNumberSuccessRouteImport.update({
    id: '/invoice/$invoiceNumber/success',
    path: '/invoice/$invoiceNumber/success',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleInvoiceInvoiceNumberFailedRoute =
  LocaleInvoiceInvoiceNumberFailedRouteImport.update({
    id: '/invoice/$invoiceNumber/failed',
    path: '/invoice/$invoiceNumber/failed',
    getParentRoute: () => LocaleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/berita/$slug': typeof LocaleBeritaSlugRoute
  '/$locale/checkout/$gameSlug': typeof LocaleCheckoutGameSlugRoute
  '/$locale/berita/': typeof LocaleBeritaIndexRoute
  '/$locale/cek-pesanan/': typeof LocaleCekPesananIndexRoute
  '/$locale/daftar-harga/': typeof LocaleDaftarHargaIndexRoute
  '/$locale/faq/': typeof LocaleFaqIndexRoute
  '/$locale/kalkulator-magic-wheel/': typeof LocaleKalkulatorMagicWheelIndexRoute
  '/$locale/kalkulator-win-rate/': typeof LocaleKalkulatorWinRateIndexRoute
  '/$locale/kalkulator-zodiac/': typeof LocaleKalkulatorZodiacIndexRoute
  '/$locale/kebijakan-privasi/': typeof LocaleKebijakanPrivasiIndexRoute
  '/$locale/leaderboard/': typeof LocaleLeaderboardIndexRoute
  '/$locale/invoice/$invoiceNumber/failed': typeof LocaleInvoiceInvoiceNumberFailedRoute
  '/$locale/invoice/$invoiceNumber/success': typeof LocaleInvoiceInvoiceNumberSuccessRoute
  '/$locale/forgot-password/': typeof LocaleAuthForgotPasswordIndexRoute
  '/$locale/login/': typeof LocaleAuthLoginIndexRoute
  '/$locale/register/': typeof LocaleAuthRegisterIndexRoute
  '/$locale/invoice/$invoiceNumber/': typeof LocaleInvoiceInvoiceNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/berita/$slug': typeof LocaleBeritaSlugRoute
  '/$locale/checkout/$gameSlug': typeof LocaleCheckoutGameSlugRoute
  '/$locale/berita': typeof LocaleBeritaIndexRoute
  '/$locale/cek-pesanan': typeof LocaleCekPesananIndexRoute
  '/$locale/daftar-harga': typeof LocaleDaftarHargaIndexRoute
  '/$locale/faq': typeof LocaleFaqIndexRoute
  '/$locale/kalkulator-magic-wheel': typeof LocaleKalkulatorMagicWheelIndexRoute
  '/$locale/kalkulator-win-rate': typeof LocaleKalkulatorWinRateIndexRoute
  '/$locale/kalkulator-zodiac': typeof LocaleKalkulatorZodiacIndexRoute
  '/$locale/kebijakan-privasi': typeof LocaleKebijakanPrivasiIndexRoute
  '/$locale/leaderboard': typeof LocaleLeaderboardIndexRoute
  '/$locale/invoice/$invoiceNumber/failed': typeof LocaleInvoiceInvoiceNumberFailedRoute
  '/$locale/invoice/$invoiceNumber/success': typeof LocaleInvoiceInvoiceNumberSuccessRoute
  '/$locale/forgot-password': typeof LocaleAuthForgotPasswordIndexRoute
  '/$locale/login': typeof LocaleAuthLoginIndexRoute
  '/$locale/register': typeof LocaleAuthRegisterIndexRoute
  '/$locale/invoice/$invoiceNumber': typeof LocaleInvoiceInvoiceNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/_auth': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/berita/$slug': typeof LocaleBeritaSlugRoute
  '/$locale/checkout/$gameSlug': typeof LocaleCheckoutGameSlugRoute
  '/$locale/berita/': typeof LocaleBeritaIndexRoute
  '/$locale/cek-pesanan/': typeof LocaleCekPesananIndexRoute
  '/$locale/daftar-harga/': typeof LocaleDaftarHargaIndexRoute
  '/$locale/faq/': typeof LocaleFaqIndexRoute
  '/$locale/kalkulator-magic-wheel/': typeof LocaleKalkulatorMagicWheelIndexRoute
  '/$locale/kalkulator-win-rate/': typeof LocaleKalkulatorWinRateIndexRoute
  '/$locale/kalkulator-zodiac/': typeof LocaleKalkulatorZodiacIndexRoute
  '/$locale/kebijakan-privasi/': typeof LocaleKebijakanPrivasiIndexRoute
  '/$locale/leaderboard/': typeof LocaleLeaderboardIndexRoute
  '/$locale/invoice/$invoiceNumber/failed': typeof LocaleInvoiceInvoiceNumberFailedRoute
  '/$locale/invoice/$invoiceNumber/success': typeof LocaleInvoiceInvoiceNumberSuccessRoute
  '/$locale/_auth/forgot-password/': typeof LocaleAuthForgotPasswordIndexRoute
  '/$locale/_auth/login/': typeof LocaleAuthLoginIndexRoute
  '/$locale/_auth/register/': typeof LocaleAuthRegisterIndexRoute
  '/$locale/invoice/$invoiceNumber/': typeof LocaleInvoiceInvoiceNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/berita/$slug'
    | '/$locale/checkout/$gameSlug'
    | '/$locale/berita/'
    | '/$locale/cek-pesanan/'
    | '/$locale/daftar-harga/'
    | '/$locale/faq/'
    | '/$locale/kalkulator-magic-wheel/'
    | '/$locale/kalkulator-win-rate/'
    | '/$locale/kalkulator-zodiac/'
    | '/$locale/kebijakan-privasi/'
    | '/$locale/leaderboard/'
    | '/$locale/invoice/$invoiceNumber/failed'
    | '/$locale/invoice/$invoiceNumber/success'
    | '/$locale/forgot-password/'
    | '/$locale/login/'
    | '/$locale/register/'
    | '/$locale/invoice/$invoiceNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/berita/$slug'
    | '/$locale/checkout/$gameSlug'
    | '/$locale/berita'
    | '/$locale/cek-pesanan'
    | '/$locale/daftar-harga'
    | '/$locale/faq'
    | '/$locale/kalkulator-magic-wheel'
    | '/$locale/kalkulator-win-rate'
    | '/$locale/kalkulator-zodiac'
    | '/$locale/kebijakan-privasi'
    | '/$locale/leaderboard'
    | '/$locale/invoice/$invoiceNumber/failed'
    | '/$locale/invoice/$invoiceNumber/success'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/register'
    | '/$locale/invoice/$invoiceNumber'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_auth'
    | '/$locale/'
    | '/$locale/berita/$slug'
    | '/$locale/checkout/$gameSlug'
    | '/$locale/berita/'
    | '/$locale/cek-pesanan/'
    | '/$locale/daftar-harga/'
    | '/$locale/faq/'
    | '/$locale/kalkulator-magic-wheel/'
    | '/$locale/kalkulator-win-rate/'
    | '/$locale/kalkulator-zodiac/'
    | '/$locale/kebijakan-privasi/'
    | '/$locale/leaderboard/'
    | '/$locale/invoice/$invoiceNumber/failed'
    | '/$locale/invoice/$invoiceNumber/success'
    | '/$locale/_auth/forgot-password/'
    | '/$locale/_auth/login/'
    | '/$locale/_auth/register/'
    | '/$locale/invoice/$invoiceNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_auth': {
      id: '/$locale/_auth'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/leaderboard/': {
      id: '/$locale/leaderboard/'
      path: '/leaderboard'
      fullPath: '/$locale/leaderboard/'
      preLoaderRoute: typeof LocaleLeaderboardIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/kebijakan-privasi/': {
      id: '/$locale/kebijakan-privasi/'
      path: '/kebijakan-privasi'
      fullPath: '/$locale/kebijakan-privasi/'
      preLoaderRoute: typeof LocaleKebijakanPrivasiIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/kalkulator-zodiac/': {
      id: '/$locale/kalkulator-zodiac/'
      path: '/kalkulator-zodiac'
      fullPath: '/$locale/kalkulator-zodiac/'
      preLoaderRoute: typeof LocaleKalkulatorZodiacIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/kalkulator-win-rate/': {
      id: '/$locale/kalkulator-win-rate/'
      path: '/kalkulator-win-rate'
      fullPath: '/$locale/kalkulator-win-rate/'
      preLoaderRoute: typeof LocaleKalkulatorWinRateIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/kalkulator-magic-wheel/': {
      id: '/$locale/kalkulator-magic-wheel/'
      path: '/kalkulator-magic-wheel'
      fullPath: '/$locale/kalkulator-magic-wheel/'
      preLoaderRoute: typeof LocaleKalkulatorMagicWheelIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/faq/': {
      id: '/$locale/faq/'
      path: '/faq'
      fullPath: '/$locale/faq/'
      preLoaderRoute: typeof LocaleFaqIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/daftar-harga/': {
      id: '/$locale/daftar-harga/'
      path: '/daftar-harga'
      fullPath: '/$locale/daftar-harga/'
      preLoaderRoute: typeof LocaleDaftarHargaIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/cek-pesanan/': {
      id: '/$locale/cek-pesanan/'
      path: '/cek-pesanan'
      fullPath: '/$locale/cek-pesanan/'
      preLoaderRoute: typeof LocaleCekPesananIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/berita/': {
      id: '/$locale/berita/'
      path: '/berita'
      fullPath: '/$locale/berita/'
      preLoaderRoute: typeof LocaleBeritaIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/checkout/$gameSlug': {
      id: '/$locale/checkout/$gameSlug'
      path: '/checkout/$gameSlug'
      fullPath: '/$locale/checkout/$gameSlug'
      preLoaderRoute: typeof LocaleCheckoutGameSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/berita/$slug': {
      id: '/$locale/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/$locale/berita/$slug'
      preLoaderRoute: typeof LocaleBeritaSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/invoice/$invoiceNumber/': {
      id: '/$locale/invoice/$invoiceNumber/'
      path: '/invoice/$invoiceNumber'
      fullPath: '/$locale/invoice/$invoiceNumber/'
      preLoaderRoute: typeof LocaleInvoiceInvoiceNumberIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_auth/register/': {
      id: '/$locale/_auth/register/'
      path: '/register'
      fullPath: '/$locale/register/'
      preLoaderRoute: typeof LocaleAuthRegisterIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/_auth/login/': {
      id: '/$locale/_auth/login/'
      path: '/login'
      fullPath: '/$locale/login/'
      preLoaderRoute: typeof LocaleAuthLoginIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/_auth/forgot-password/': {
      id: '/$locale/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password/'
      preLoaderRoute: typeof LocaleAuthForgotPasswordIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/invoice/$invoiceNumber/success': {
      id: '/$locale/invoice/$invoiceNumber/success'
      path: '/invoice/$invoiceNumber/success'
      fullPath: '/$locale/invoice/$invoiceNumber/success'
      preLoaderRoute: typeof LocaleInvoiceInvoiceNumberSuccessRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/invoice/$invoiceNumber/failed': {
      id: '/$locale/invoice/$invoiceNumber/failed'
      path: '/invoice/$invoiceNumber/failed'
      fullPath: '/$locale/invoice/$invoiceNumber/failed'
      preLoaderRoute: typeof LocaleInvoiceInvoiceNumberFailedRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleAuthRouteRouteChildren {
  LocaleAuthForgotPasswordIndexRoute: typeof LocaleAuthForgotPasswordIndexRoute
  LocaleAuthLoginIndexRoute: typeof LocaleAuthLoginIndexRoute
  LocaleAuthRegisterIndexRoute: typeof LocaleAuthRegisterIndexRoute
}

const LocaleAuthRouteRouteChildren: LocaleAuthRouteRouteChildren = {
  LocaleAuthForgotPasswordIndexRoute: LocaleAuthForgotPasswordIndexRoute,
  LocaleAuthLoginIndexRoute: LocaleAuthLoginIndexRoute,
  LocaleAuthRegisterIndexRoute: LocaleAuthRegisterIndexRoute,
}

const LocaleAuthRouteRouteWithChildren = LocaleAuthRouteRoute._addFileChildren(
  LocaleAuthRouteRouteChildren,
)

interface LocaleRouteRouteChildren {
  LocaleAuthRouteRoute: typeof LocaleAuthRouteRouteWithChildren
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBeritaSlugRoute: typeof LocaleBeritaSlugRoute
  LocaleCheckoutGameSlugRoute: typeof LocaleCheckoutGameSlugRoute
  LocaleBeritaIndexRoute: typeof LocaleBeritaIndexRoute
  LocaleCekPesananIndexRoute: typeof LocaleCekPesananIndexRoute
  LocaleDaftarHargaIndexRoute: typeof LocaleDaftarHargaIndexRoute
  LocaleFaqIndexRoute: typeof LocaleFaqIndexRoute
  LocaleKalkulatorMagicWheelIndexRoute: typeof LocaleKalkulatorMagicWheelIndexRoute
  LocaleKalkulatorWinRateIndexRoute: typeof LocaleKalkulatorWinRateIndexRoute
  LocaleKalkulatorZodiacIndexRoute: typeof LocaleKalkulatorZodiacIndexRoute
  LocaleKebijakanPrivasiIndexRoute: typeof LocaleKebijakanPrivasiIndexRoute
  LocaleLeaderboardIndexRoute: typeof LocaleLeaderboardIndexRoute
  LocaleInvoiceInvoiceNumberFailedRoute: typeof LocaleInvoiceInvoiceNumberFailedRoute
  LocaleInvoiceInvoiceNumberSuccessRoute: typeof LocaleInvoiceInvoiceNumberSuccessRoute
  LocaleInvoiceInvoiceNumberIndexRoute: typeof LocaleInvoiceInvoiceNumberIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAuthRouteRoute: LocaleAuthRouteRouteWithChildren,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBeritaSlugRoute: LocaleBeritaSlugRoute,
  LocaleCheckoutGameSlugRoute: LocaleCheckoutGameSlugRoute,
  LocaleBeritaIndexRoute: LocaleBeritaIndexRoute,
  LocaleCekPesananIndexRoute: LocaleCekPesananIndexRoute,
  LocaleDaftarHargaIndexRoute: LocaleDaftarHargaIndexRoute,
  LocaleFaqIndexRoute: LocaleFaqIndexRoute,
  LocaleKalkulatorMagicWheelIndexRoute: LocaleKalkulatorMagicWheelIndexRoute,
  LocaleKalkulatorWinRateIndexRoute: LocaleKalkulatorWinRateIndexRoute,
  LocaleKalkulatorZodiacIndexRoute: LocaleKalkulatorZodiacIndexRoute,
  LocaleKebijakanPrivasiIndexRoute: LocaleKebijakanPrivasiIndexRoute,
  LocaleLeaderboardIndexRoute: LocaleLeaderboardIndexRoute,
  LocaleInvoiceInvoiceNumberFailedRoute: LocaleInvoiceInvoiceNumberFailedRoute,
  LocaleInvoiceInvoiceNumberSuccessRoute:
    LocaleInvoiceInvoiceNumberSuccessRoute,
  LocaleInvoiceInvoiceNumberIndexRoute: LocaleInvoiceInvoiceNumberIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
